### ISSUE TITLE
Can only  part of rust function be used?

### ISSUE THREAD

**Issue by Zhongguadedou** [vectordotdev/vector#10112]
### Current Vector Version

```
0.17.0
```

### Phenomenon

Only support part of rust function in the Transforms. (https://vector.dev/docs/reference/vrl/functions/)

### Proposal

Support more functions of rust, just like read file， use database and so on

**Comment by Zhongguadedou** [comment]
@binarylogic

**Comment by jszwedko** [comment]
Hi @Zhongguadedou !

VRL is not intended to be a full programming language like Rust. It is specifically designed for data processing and intended to be a simple and performant language for users to use for mapping data in Vector. As part of this, we design functions to have high performance and not allow for expensive I/O operations (like reading from a file). There is a [VRL design document](https://github.com/vectordotdev/vector/blob/master/lib/vrl/DESIGN.md) that describes this more in-depth. We add more and more functions as there is demand for them.

However, there is a `lua` transform that does allow you to take advantage of a full programming language, Lua, when needed. Ideally VRL will support all transformations but Lua can be used as for more complex processing that VRL doesn't yet support. It also supports slow operations like reading from files or interacting with a database.

Does this make sense? Let me know if you have any other questions! I'll close this since we don't intend to just expose Rust directly to the end-user, but I'm happy to discuss your use case more to see if we could support it better.
