### ISSUE TITLE
Add baseline benchmarks for `match_datadog_query` VRL function

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#10151]
As part of #10144, we have identified that `match_datadog_query` is in a hot path for the processing of Pipelines due to the extensive use of Datadog Search Syntax conditions.

Before we attempt optimisations on this VRL, it would be useful to get a baseline for the current performance to assess against.

**Comment by vladimir-dd** [comment]
I've created a minimum test config with 35 empty pipelines, so that only pipeline filters(which call `match_datadog_query` inside) apply to incoming events. 
After [optimization](https://github.com/vectordotdev/vector/pull/10189) we have consumed an input file with 10000 of events in <4sec vs 8min 20 sec before, which is 100+x improvement.
