### ISSUE TITLE
Investigate improving the performance of end-to-end acknowledgements

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#10291]
The soak tests introduced to monitor the behavior of end-to-end acknowledgements in #10255 have indicated that, for simple configurations, enabling acknowledgements can cut throughput by a factor of four. We believe this is due to the increase in latency caused by the acknowledgement system and not due to any significant increase in processing time, but it would be worth spending some time investigating if this is actually true and what could be done to improve this performance metric.

**Comment by jszwedko** [comment]
I tried out bumping the number of concurrent connections in https://github.com/vectordotdev/vector/pull/10300 as we had a hypothesis that maybe the effects of e2e acks on overall throughput would decrease with more connections, but it does not seem to have had an impact:

10 connections:

```
http_to_http_acks 5.94MiB
http_to_http_noack 19.27MiB
```

100 connections:

```
http_to_http_acks 6.12MiB
http_to_http_noack 17.57MiB
```

**Comment by bruceg** [comment]
In private discussion, @binarylogic raised the idea of optionally adding a (disk) buffer to sources. This would allow a source to acknowledge events as soon as they were persisted to the buffer instead of waiting for them to go through the topology. This should improve latency (and hence performance) in topologies where there is either significant processing happening in transforms or where at least one destination sink is not using disk buffers and so is waiting for a remote to acknowledge requests. Of course, the events would then have to be streamed out of the buffer through the topology, so this could reduce performance in the non-acknowledgements case, but not any more so than having buffers on sinks.

Thoughts? @tobz @blt

**Comment by binarylogic** [comment]
@bruceg I do think disk-buffers are an interesting work around for the performance problems, but there are cases where disk-buffers should not be used and e2e acking should be performant. For example, a `kafka` source and `kafka` sink pipeline should not use buffers since Kafka itself is a buffer. In this case, Vector should be utilizing e2e acking and it should be performant. So, if it helps, let's focus on that use case in the interest of improving performance of this feature.

**Comment by blt** [comment]
Possibly related to #10332

**Comment by blt** [comment]
I'm curious what the failure modes we have documented for e2e acking are. If a system emits into vector and vector acks, does that imply that the emitted data has made its way through vector or it will eventually make its way through, with some confidence? I understood the former, not the later. If the later, I think the disk buffer notion might work, keeping in mind that the data buffered to disk is only as stable as the underlying disk. The later interpretation would be counter to kafka's assumptions, in the case of kafka -> kafka about acking. 

I'm curious if we have data right now on why acking has such strong performance implications?

**Comment by jszwedko** [comment]
I think we need to dig in more. It will necessarily have an impact on an individual client/connection since the request latency, from a client perspective, has now increased by the sum of the processing time in Vector + the latency of requests in the sink. We expected with more concurrent requests that this impact would lessen, though, and were surprised by the results I mentioned in https://github.com/vectordotdev/vector/issues/10291#issuecomment-987128683

> If a system emits into vector and vector acks, does that imply that the emitted data has made its way through vector or it will eventually make its way through, with some confidence?

For in-memory buffers, it will wait to ack until after the sink has sent it (given different sinks have different guarantees; e.g. a `socket` sink can just guarantee that it wrote the data to the socket). For disk buffers, it will ack as soon as the buffer accepts it, before the sink even sees it. I think the thought is that this offers some measure of "durability" such that events will eventually be sent.

Regarding the source buffer idea, I think we should aim to have e2e acking be as performant as we expect it to be without disk buffers as this is our most common recommendation to partners. Once we get performance for that scenario to where we expect, we can then consider suggesting disk buffers for cases where customers want higher throughput and find the guarantees afforded by disk buffers (or remote buffers when we add those) acceptable.

**Comment by bruceg** [comment]
The performance observed in the soak tests indicates that end-to-end acks currently has only a small performance impact for all tests except for `http_to_http_acking`. That performance drop is being tracked in #10543, so we can close this one until further issues are observed.
