### ISSUE TITLE
Update vector top for multiple outputs

### ISSUE THREAD

**Issue by 001wwang** [vectordotdev/vector#10871]
We should update vector `top`'s TUI to deal with statistics for named outputs

**Comment by lukesteensen** [comment]
Giving each output it's own row makes sense to me. We could also add another column after ID that's `Output` and contains the name of the output or empty for the default. If we wanted to get really fancy we could make the top-level a summary of all outputs and have a collapsable list with the per-output stats, including `_default`, but that doesn't seem necessary as a first pass.

**Comment by leebenson** [comment]
With us already being constrained on the horizontal, implementing a layout similar to @lukesteensen's suggestion of hiding data until it's selected might make sense.

A collapsable list might be difficult in the current design, because we don't have any logic to handle vertical offsets/scrolling. If a user selects, say, the last row of the list... it would collapse out of view.

If you wind up going down this road, one option might be to make each row selectable/clickable, and then navigate to a dedicated view with the additional columns taking advantage of a fuller vertical layout. 

[tui-rs](https://github.com/fdehau/tui-rs) has some nice examples for implementing mouse/keyboard handlers, making rows selectable, and navigating between screens.

With all that said, I imagine the engineering effort of making those changes could be quite large. If it's likely we're _only_ going to need this column for a while, you might be able to squeeze it in. If there are likely to be other columns we want to add later, then investing the time in a more dedicated screen could be justified.

**Comment by jszwedko** [comment]
Agreed, I like the idea of having an expandable row, but I also have no idea how much effort that would be with the TUI framework we are using. If we did do that, I think it'd be something like:

* Each component would have its own row where the metrics represent the sum of all outputs
* You could select the row to expand it and see each output listed below

As a first iteration I think what you mocked up looks good to me; we should just ensure that named outputs are grouped immediately under their component. Additionally, I would just leave `Kind`, `Type`, and `Events In` blank for named outputs. I think this will visually group them with the row for the component.
