### ISSUE TITLE
`journald` source needs a `batch.timeout` option

### ISSUE THREAD

**Issue by nbrownus** [vectordotdev/vector#11187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.19.1 (x86_64-unknown-linux-gnu 3cf70cf 2022-01-25)
```

### Use-cases

A high throughput `journald` source with `acknowledgements.enabled` when paired with a sink that batches output.

### Attempted Solutions

An example config:
```
[sources.journald]
    type = "journald"
    acknowledgements.enabled = true
    batch_size = 500

[sinks.firehose]
    type = "aws_kinesis_firehose"
    inputs = [ "journald" ]
    stream_name = "logs"
    encoding.codec = "json"
    ...
```

This works well to fill the default batch of the `firehose` sink (500) assuming there are at least 500 events in the `journald` source. Once the backlog in the `journald` source is consumed the source appears to block until it has met the `batch_size` threshold.

### Proposal

Use the same `batch.max_events` and `batch.timeout` pattern that sinks use in sources that can batch. This would allow for quick consumption of a backlog and keeping up with a high logging host while not penalizing slow logging periods too much.

### References

#9856

**Comment by jszwedko** [comment]
Hi @nbrownus !

Thanks for filing this. I just want to make sure I understand the request here to see how your proposal would address it.

It sounds like you have a `journald` source feeding into an `aws_kinesis_firehose`. If the `journald` source has no events to consume, the `aws_kinesis_firehose` sink waits (since it is waiting for 500 events). If there are no more events for `journald` to process, what would setting the batch size on the source do? Either way, it seems like the sink would wait for 500 events (or the `batch.timeout_secs` to expire, which defaults to 1s). I get the sense that I'm likely missing a piece 😄

**Comment by nbrownus** [comment]
It's not that the `journald` source has no events, it may have low and high velocity period of events. Ultimately all logs will be delivered as it stands today, just some with possibly incredible delays due to the `journald` source waiting until it has filled the configured batch size.

What I am trying to accomplish is a timely delivery of all events, despite the current log velocity in `journald`.

Consider a host that logs 50k events/second between 8am and 5pm Mon-Fri, and logs 1 event/seconds all other times. To ensure the timely delivery at the high velocity times I tune the `journald` and `aws_kinesis_firehose` batch sizes to 50,000. This gives me a delay of around 1 second. When the low velocity time hits it would take nearly 14 hours before the `journald` source batch fills and releases it to `aws_kinesis_firehose` sink.

**Comment by jszwedko** [comment]
Thanks for clarifying @nbrownus !

The problem makes sense, but I'm still not seeing how configuring a batch size on the source would help address it.

Would simply configuring `batch.timeout_secs` on the sink address this problem? It defaults to 1 second which means that the `aws_kinesis_firehose` sink would not wait 14 hours but simply flush the 1 event it got in the last second during the period of low volume. During the period of high volume, if the `batch.max_events` is set to, say, 10k, then it would flush 5 times a second during the period of high volume.

**Comment by nbrownus** [comment]
My proposal is for `batch.timeout` on the source

**Comment by jszwedko** [comment]
> My proposal is for `batch.timeout` on the source

Right, yeah, I see. Does `batch.timeout_secs` on the sink not satisfy the need here though?

I can see that this setting might be useful with a sink consuming from multiple inputs where you want them to have different batch timeouts. Though, it'd be a bit awkward in that case because batches will contain events from multiple inputs so the lowest batch setting would effectively win out; unless we partitioned the batches by input.

Apologies if I'm being dense, just trying to understand the use-case here 🙂

**Comment by nbrownus** [comment]
> Apologies if I'm being dense, just trying to understand the use-case here 🙂

No this is a fairly complex one, or I am making it too complex :D

With `acknowledgements.enabled = true` on the `journald` source the behavior seems to be:

1. `journald` blocks until `batch_size` is met
2. `journald` releases the batch to `aws_kinesis_firehose`, `journald` is now blocked until ack from sink
3. `aws_kinesis_firehose` waits until `batch.max_events` or `batch.timeout_secs` is met
4. `aws_kinesis_firehose` sends batch to the firehose
5. `aws_kinesis_firehose` acks back to `journald`
6. `journald` can now move onto the next batch

If the `journald` `batch_size` is too small for the `aws_kinesis_firehose` `batch.max_events`, then `batch.timeout_secs` is in play and the maximum throughput is roughly `journald` `batch_size` / `aws_kinesis_firehose` `batch.timeout_secs` since the source will not allow more than 1 batch to be outstanding at a time.

If `journald` `batch_size` is bigger than or equal to `aws_kinesis_firehose` `batch.max_events` then throughput is roughly however fast the system can fill `journald` `batch_size`.

If `journald` had a `batch.timeout` then I could tune the batch sizes to be as big as `aws_kinesis_firehose` will allow while keeping the worst batch latency cost at 1s.

**Comment by jszwedko** [comment]
Aha! I completely missed that `journald` also reads in batches 🤦 I see what you are saying now. That "read in a configurable batch" behavior makes this source a bit of an oddball. I could definitely see adding a timeout option there if we keep the batch configuration but I am thinking we might want to remove it altogether and just have the source read and send events as it has them, rather than waiting for full batch. I'll think about this a bit more.

**Comment by nbrownus** [comment]
I believe the batch behavior is because vector maintains a cursor in the journal for some level of fault tolerance. When that is coupled with `acknowledgements.enabled = true` I can get a pretty strong guarantee that logs from a given host have at least made it into the firehose, or have entirely stalled, the latter being signal that I can monitor/alert on. Once in the firehose there are other mechanisms to detect/recover from failures, the end result being a highly durable/scalable log pipeline.
