### ISSUE TITLE
Improve VRL's type checking logic for coalesced paths

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#11249]
Given:

```coffee
.foo = "foo"
.bar = true
.(foo | bar)
```

The type definition for the result of that path query should be "string" because the value is known to never return `null`, and coalesced path segments are processed from left to right. Currently, it returns "string OR boolean" because it doesn't stop processing after it has processed a coalesced field that can never return null at runtime.

This isn't a bug, in that the type information isn't _incorrect_, it's merely _incomplete_, we can do better, when we get the chance to improve this.

**Comment by fuchsnj** [comment]
https://github.com/vectordotdev/vector/issues/13459 will be required to fully implement this. This can be implemented for _some_ cases, such as the example above, but coalescing uses the first _defined_ value (not the first non-`null` value), and our type system cannot differentiate in all cases between `null` and `undefined` today.

Notice in this example the null value is overwritten, since it is defined. (We have a concept of defined/undefined at _runtime_ but not in the type system)

I also found an existing but related to this in `kind::insert_at_path`, but that will be fixed as part of https://github.com/vectordotdev/vector/issues/13505

### Example
```coffeescript
$ .a = null
null

$ .(a|b) = 5
5

$ .
{ "a": 5 }
```
