### ISSUE TITLE
Disk buffers acknowledge failed events when end-to-end acks are enabled

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12145]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

This was intended behavior, but we think this isn't the correct behavior when considering end-to-end acknowledgements.

If a sink rejects an event (`DeliveryStatus::Rejected`) the disk buffer considers this event processed and moves on. This is OK under normal operation, but if a sink has end-to-end acknowledgements configured (`acknowledgements = true`) then the behavior is a bit surprising as this feature is meant to provide delivery guarantees for the source that data was processed by the sink (or eventually will be if disk buffers are involved).

Instead, the disk buffer should block on the rejected event and let an operator intervene to fix it.

As part of fixing this behavior, we will likely want to add in mechanisms for Vector operators to handle this situation. They may want to, for example, manually advance Vector past the rejected event.

Routing rejected events from sinks ("dead letter queues") will also help mitigate this issue.

### Tasks

- [x] #13020
- [x] #13023
- [ ] #13472
- [ ] #13563
- [ ] #13575

---

Split off:

- [ ] #9857 
- [ ] Clean up `acknowledgements` configuration for sinks after they all support it
- [ ] #13397

**Comment by bruceg** [comment]
@tobz and I discussed this, from which I remember the following points:
* Event finalization provides two signals: the time when an event/batch has completed handling and the final status of that event/batch.
* The `Acker` provides a signal to the disk buffer when a set of events has completed handling by a sink.
* The `OrderedFinalizer` handles ordering of finalizers similar to how sinks handle ordering through `Acker`.
* Buffers don't send data to sinks, the sinks pull it from the buffer through a `Stream`.
* Selective acknowledgement of events in the buffer is hypothetically possible but would require a on-disk format change and the overhaul of many assumptions about record sequences.

So, the implementation plan for this is:
1. Add at least the minimal support for delaying finalizing events in all sinks until events are delivered. This is effectively one part of supporting full end-to-end acknowledgements in all sinks (#9857) just without handling the actual status. [According to the docs](https://github.com/vectordotdev/vector/tree/master/website/cue/reference/components/sinks), this would only be required for 8 sinks, some of which would be trivial (ie `console`).
2. Since all sinks now finalize events at the same time as they acknowledge them to the disk buffer, replace the `Acker` type with the `OrderedFinalizer` wrapper around the existing event finalizers.
3. Add support at the disk buffer level for closing/fusing the output stream when a negative acknowledgement is received.
4. Provide some kind of tool (how?) for users to manually advance the disk buffer over a failed event. Possible options are an API hook, a config setting to "skip this buffer ID", or an offline tool to manipulate the buffer files.

Steps 1 and 2 above can proceed in parallel, but the latter won't work correctly until the former is complete.

**Comment by bruceg** [comment]
Outstanding question:
1. What kind of metric should we emit to expose this condition?
2. Do we want or need to emit a signal beyond this metric that a sink has shut itself down due to a negative acknowledgement?

**Comment by bruceg** [comment]
In light of our renewed focus on [upfront configuration instead of manual intervention](https://github.com/vectordotdev/vector/blob/master/docs/USER_EXPERIENCE_DESIGN.md#upfront-configuration), we are closing this epic to focus on other methods of handling errors during event delivery, namely infinite retries and dead letter queues.

Ref #13624
