### ISSUE TITLE
prometheus_scrape can't crawl from keycloak metrics

### ISSUE THREAD

**Issue by darjeeling** [vectordotdev/vector#12804]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

`prometheus_scrape` can't crawling from keycloak metrics.
because `keycloak` dose not accept "accept-encoding: identity"

```
curl -v -H "Accept:" -H "accept-encoding: identity" http://localhost:8080/metrics
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> accept-encoding: identity
>
< HTTP/1.1 406 Not Acceptable
< content-length: 69
<
* Connection #0 to host localhost left intact
* ```


### Configuration

```text
[sources.keycloak_metrics]
type = "prometheus_scrape"
endpoints = [ "http://localhost:8080/metrics" ]
endpoint_tag = "endpoint"
scrape_interval_secs = 10
```

### Version

vector 0.21.2 (x86_64-unknown-linux-gnu 1f01009 2022-05-05)

### Additional Context

I think default http client should provide http header override.
without that, we can't handle it properly

**Comment by hhromic** [comment]
According to the HTTP spec here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
```
      4. The "identity" content-coding is always acceptable, unless
         specifically refused because the Accept-Encoding field includes
         "identity;q=0", or because the field includes "*;q=0" and does
         not explicitly include the "identity" content-coding. If the
         Accept-Encoding field-value is empty, then only the "identity"
         encoding is acceptable.
```

The `identity` encoding (as you indicate Vector is sending) MUST be acceptable by any remote server. So I'm not sure Vector is doing anything wrong here. This sounds more like a bug to report to keycloack instead?

**Comment by darjeeling** [comment]
@hhromic it make sense and I think it sound right.
but as you know if vector have some option to override request header. I can use it till the server fixed
how about it?
maybe I didn't find proper config option. but it should be documented

**Comment by hhromic** [comment]
@darjeeling , I agree having options to override headers is nice to have.

However, I think that a better idea in this case would be for Vector to support HTTP compression in this source.
Some sources/sinks already support setting `compression: gzip`, unfortunately this is not the case for `prometheus_scrape` :(
If compression support is added, we also get the benefit of compressed transfer for less bandwidth usage.

Can you confirm if keycloak supports compression by using `--compressed` in your `curl` invocation?
```
curl -v --compressed http://localhost:8080/metrics
```
You should see `curl` sending a header like this to keycloak:
```
Accept-Encoding: deflate, gzip, br, zstd
```
If keycloak responds correctly to that, I think compression support would be a low-hanging fruit implementation in Vector to add.

**Comment by darjeeling** [comment]
@hhromic hmm. it dose not work.
I need to read more RFC.
```
url -v -H "Accept:" --compressed http://localhost:8080/metrics
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> Accept-Encoding: deflate, gzip
>
< HTTP/1.1 406 Not Acceptable
< content-length: 69
<
* Connection #0 to host localhost left intact
Couldn't determine a suitable media type for the given Accept header.
```

**Comment by darjeeling** [comment]
@hhromic 
IMHO if `vector` has workaround way of some. 
I think it will be very helpful when deploy `vector` on my working company wide.
it's very fast and efficient

**Comment by hhromic** [comment]
@darjeeling you should stop passing the `-H "Accept:"` flag into `curl`. That is affecting `--compressed` to not work.
You should leave that flag out and then `curl` will be able to send the correct `Accept` header for `--compressed`.

In other words, just try the command like this:
```
$ curl -v --compressed http://localhost:8080/metrics
```

Nonetheless, the response you got in the keycloak issue you opened shed light that Vector, while not doing anything wrong in my honest opinion, could still behave a bit better by supplying an `Accept` header with `text/plain` (as suggested by the official [text exposition format documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) from Prometheus).

Note that I still think that the keycloak server should accept a missing `Accept` header that Vector is not providing. This is correct HTTP as far as the standards say. Keycloak is misbehaving in this regard which is the real issue here. They really should fix that regardless. I have used the `prometheus_scrape` source with different exporters and they all work fine.

In my very personal opinion (which does not represent the opinion of the Vector team), adding configurable headers for your use-case allows for masking the actual problem more than solving it, which is why my opinion is more about adding the missing `Accept` header and/or adding compression support than freely allowing to modify headers for this source.

**Comment by hhromic** [comment]
The issue was propagated from `keycloak` to `smallrye-metrics`, where the problem actually was: https://github.com/smallrye/smallrye-metrics/issues/497

A PR with a fix has been sent and merged already by a keycloak maintainer :)
So, the keycloak server will be fixed sooner than later probably.

I still would recommend for Vector to implement sending `Accept: text/plain` for the `prometheus_scrape` source to improve compatibility with flaky servers in the future.

**Comment by hhromic** [comment]
@darjeeling can you confirm if this command works for your instalation of keycloak then?
```
$ curl -v -H "Accept: text/plain" -H "Accept-Encoding: identity" http://localhost:8080/metrics
```

**Comment by darjeeling** [comment]
@hhromic it works well with that command.

Thanks for your help :)
