### ISSUE TITLE
Publish `INFO` messages for each batch being processed by a component

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#12968]
This helps give users more confidence that Vector is operating correctly.

**Comment by spencergilbert** [comment]
I'm curious why at INFO, it seems like a DEBUG level to me

**Comment by jszwedko** [comment]
Talked about this offline, but my motivation is for `vector` to show activity at the `INFO` level while processing data. I think it is pretty typical to log an `INFO` message when you, for example, process an HTTP request in a web app. In Vector’s case, I think processing a batch is the closest operation.

**Comment by hhromic** [comment]
> I'm curious why at INFO, it seems like a DEBUG level to me

In my humble opinion, I also think this is DEBUG level information that you want to see when developing a pipeline, not in production, where you don't want spamming/noisy components but instead you properly monitor using exported metrics.

As a further argument, Vector spamming the console output can easily lead to Vector filling the disk with logs on systems without proper log pruning (which is not so uncommon). I don't think constant logging by default is good behaviour.

I hope you can reconsider _not_ using INFO level logging for processed batches.

**Comment by hhromic** [comment]
Thanks for the reply @jszwedko !
I'm definitively not an authority on logging levels and I think nobody really is as this is very subjective topic and ultimately depends on the goals of the developers/use-case.

I raised the voice into the subject because rarely any software we are running is "spammy" at the INFO level. So Vector will be a first! I did consider setting WARN as the logging level but then we will miss actually useful INFO-level messages. But I guess that will have to do if the Vector team is fully sold on logging batches with INFO. We definitively don't want INFO messages every second (the configured period of all of our batches).

I was thinking, given that Vector seems to already support differentiated loggers:
```
2022-06-07T14:06:36.898819Z  INFO vector::app: Log level is enabled. level="vector=info,codec=info,vrl=info,file_source=info,tower_limit=trace,rdkafka=info,buffers=info"
```

Would it make sense to have a "batches" logger for logging batching activity? That way we could configure "batches.level=warn" (and leave the rest as "info") and result in the same behaviour we have today. I believe everybody would be happy.
