### ISSUE TITLE
Add facility to advance disk buffer in the case of poison pill events

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#13472]
There are several general approaches to provide this facility:
1. Create a command-line tool to manually advance the disk buffer ledger past a broken record. Using this tool would require the user to restart vector after running the tool, at minimum, and may need to have vector stopped before updating the ledger. It may also require information from the logs (a record number) to inform which record to advance past.
2. Add an parameter to the disk buffer configuration that indicates that it should skip past certain records. This would require the user to update their configuration and then restart or reload vector, and would likely need the poisoned record number from the logs to prevent data loss on a later restart.
3. Add a flag to the ledger that the first record to read was poisoned and also add a parameter to the buffer configuration to skip any poisoned records. This would require a vector reload and possibly restart.
4. Add an API hook that would allow the user to advance the buffer past the poisoned record, and a command-line tool to invoke that API. This would allow for fixing this condition with no interruptions to the data flow, but would be the most involved solution in terms of development time.

Related: #13050

**Comment by jszwedko** [comment]
👍 thanks for writing these up @bruceg 

I agree that option 4 has the best UX (including interactivity and not needing to stop a running Vector instance), I'm just slightly concerned about the implementation effort that might be involved. Do you think you might be able to do a quick spike and see the effort that would be required here?

Failing that, option 1 sounds like the most straight forward to me.

**Comment by bruceg** [comment]
>  Do you think you might be able to do a quick spike and see the effort that would be required here?

If I'm reading the API sources right, the existing schema doesn't expose the buffer info at all. It's not clear if there are any objects in the schema that can be mutated either, which would be necessary to modify the buffer ledger. So option 4, unfortunately, looks like it would take a good deal of time to set up the API.

I would, of course, be quite happy to be told I'm wrongly pessimistic here from somebody who has actual knowledge of the API code. @leebenson?

**Comment by bruceg** [comment]
I discussed this with @001wwang and this is my understanding:
* The API does not expose any details of the buffers. In particular, the API only exposes the names, types, and inputs of sinks.
* Wiring up to expose additional data for querying the buffers is pretty simple from a API point of view. It will likely be more work to expose the data internally, given that buffers have their own topology now, but that shouldn't be all that hard.
* There is nothing in vector that allows for modifications through the API (called "mutation"), but the underlying crate supports it and we use it in the OP interface. So, there would be some boilerplate that needs to be added which would likely be the biggest part of the work to support the updates.
* This would still require a CLI to connect, query, and mutate the buffer state, but we could copy a lot of that from the existing "top" tooling.

**Comment by bruceg** [comment]
I have taken a couple stabs at implementing the API hooks and gave up for now due to too much additional plumbing being needed all over:
1. The API data for components (sinks in this case) is currently pulled from the config and not the running topology. So, it would need a hook into the topology to access info about the running sink's buffer.
2. The topology doesn't actually have a handle on the buffer details, only the send and receive handles for the channel. So, it would need a hook into the buffer to access its state.
3. Returning _the_ ledger for the buffer is messy at best as the buffer code is set up to produce a _topology_ of buffers.

So I am back to writing a simple CLI to tweak the ledger. Regarding the UX, would it be preferable to have the tool:
1. Set the read record ID to a given value? This has potential problems with copy-paste typo issues corrupting the ledger.
2. Just bump up the last read ID by one? This has the potential problem of skipping too many records if run more than once.

**Comment by tobz** [comment]
So, this gets tricky because we can't simply increment record IDs in the ledger by one: they represent the event count, so they aren't sequential.

Maybe what could work is an unsafe method that specifically reads the next record and positively acknowledges it blindly? With that, we don't risk the copypasta issue, because we know exactly how to increment it, it's just the normal logic once we trigger a positive acknowledgement. This approach doesn't, however, address anything about overskipping records... but maybe we just make the command interactively require input (i.e. entering "yes") so it can't be trivially re-run on accident?

**Comment by leebenson** [comment]
FWIW, the current approach taken in the API to copy over the component ID and meta was intended to be a non-invasive starting point way back when, in lieu of topology hooks. I'd favour improving this, such that a ref to running topology could be passed in to the API server, and querying could be done directly instead of against a representation of it. This could make it easier to probe internals.

That's tangential, since we'd still need some kind of internal API for exposing buffer state within topology, but just an FYI that improving this has been an intention for a while. This might be a good enough reason to do it.

**Comment by bruceg** [comment]
Closed to pursue other approaches, see https://github.com/vectordotdev/vector/issues/12145#issuecomment-1191688809
