### ISSUE TITLE
Vector stops everything if one of the sinks return 503 status

### ISSUE THREAD

**Issue by namm2** [vectordotdev/vector#13679]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Currently I have Vector aggregator to send logs to 2 sinks: Elasticsearch and Humio, when one sink downstream returns HTTP 503 status Vector will halt everything including Vector agent backoffs and stops sending events.

My expectation is if one sink is unavailable, Vector would keep sending logs to the rest that passed healthcheck instead of just stops everything down the chain.

### Configuration

```text
customConfig:
  sources:
    kubernetes:
      type: vector
      address: 0.0.0.0:9080
      version: "2"
  transforms:
    ...
    last_transform:
      type: remap
      inputs:
        - previous_transform
      source:
        ...
    filtered:
      type: filter
      inputs:
        - last_transform
      condition:
        type: "vrl"
        source: |-
          .field != "something"


  sinks:
    elk:
      doc_type: doc
      inputs:
        - last_transform
    humio:
      type: humio_logs
      inputs:
        - filtered
      encoding:
        codec: json
      compression: gzip
      # To reproduce the issue
      host: https://httpstat.us/503
```

### Version

0.21

**Comment by roumigus** [comment]
> My expectation is if one sink is unavailable, Vector would keep sending logs to the rest that passed healthcheck instead of just stops everything down the chain.

According to https://vector.dev/docs/about/concepts/#buffers and https://vector.dev/docs/about/concepts/#backpressure, this behavior is intended.

By setting `buffer.when_full` to `drop_newest`, the sink (in the config example: Humio) would not propagate backpressure. Logs would therefore keep flowing from the source to the other sinks (in the config example: Elasticsearch).

The confusing thing is that this backpressure mechanism seems to apply (whenever we have `buffer.when_full: block`) even though the option  `acknowledgments.enabled` is set to `false` by default.

I thus assume that `acknowledgments.enabled: true` has no effect on the propagation of backpressure. I guess the acknowledgments feature is really only about communicating explicit ACKs with the sources that can understand this concept (such as queues system: s3, gcp pubsub, kafka...) instead of simply stop reading logs (which is controlled by `buffer.when_full: block` and works with sources not implementing acknowledgments such as `kubernetes_logs`).

Can someone confirm?

**Comment by jszwedko** [comment]
Hi @namm2 and @roumigus !

As you note, this behavior is expected for the default buffer configuration. You can set `buffer.when_full = "drop_newest"` to have a sink just shed data when the downstream is unavailable rather than block.

`acknowledgements.enabled` controls whether any sources that are connected to the given sink wait to acknowledge incoming data until it has successfully made it to the sink. For example, for the `http` source, it will wait to issue the HTTP response until the connected sink has received the data. If it is `false` this just means the source will acknowledge the incoming data as soon as it receives it rather than waiting. Note that not all sources support acknowledgements (e.g. the `socket` source does not), in which case the setting does not apply (you should see a warning in Vector's logs when configuring `acknowledgements.enabled` on a sink with connected sources that don't support them). The `kubernetes_logs` source actually does support acks by waiting to mark lines in files as "read' (via Vector's internal checkpointing) until the sink has processed them.

Hopefully this helps clear things up! Let me know if you have any follow-up questions!

**Comment by jszwedko** [comment]
I'll close this since I think the questions have been answered, but please feel free to leave any additional ones.

**Comment by roumigus** [comment]
Thank you for this confirmation @jszwedko :slightly_smiling_face: 

One last thing, to avoid any confusion. You mentioned:

> The kubernetes_logs source actually does support acks by waiting to mark lines in files as "read' (via Vector's internal checkpointing) until the sink has processed them.

However the documentation explicitely says it does not (the badge `acknowledgements: no` at the top of [the kubernetes_logs source configuration reference page](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/))

In the source code it also looks like the acknowledgment feature is not yet implemented:
```bash
vector/src/sources/kubernetes_logs master $ rg -C 2 acknowledg .
./mod.rs
215-    }
216-
217:    fn can_acknowledge(&self) -> bool {
218-        false
219-    }

./util.rs
30-    let join_handle = spawn_blocking(move || {
31-        // These will need to be separated when this source is updated
32:        // to support end-to-end acknowledgements.
33-        let shutdown = shutdown.shared();
34-        let shutdown2 = shutdown.clone();
vector/src/sources/kubernetes_logs master $
```

Is that correct? Or is the source implementing ACK anyway and the documentation (and some parts of the code/comments) are outdated?

**Comment by jszwedko** [comment]
Hi @roumigus ! You are right, the `kubernetes_logs` source does not support it. I was thinking of the `file` source, which does. Seemingly the `kubernetes_logs` source _could_ support it though, in the same manner the `file` source does by waiting to write the checkpoint of how far it has read in each file until the acknowledgement is received.
