### ISSUE TITLE
Do not run vector if the sum of max_buffer_size is greater than the disk size

### ISSUE THREAD

**Issue by 3g0r** [vectordotdev/vector#14348]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Hi all.

I am using vector in k8s and control buffer size via container env vars.
I can forget about the maximum volume size under the vector by increasing the size of the buffers.
This will cause data corruption errors.

I think the vector could check the available disk size and compare it to the sum of the maximum buffer sizes for all syncs at startup, and disconnect if there is no required disk space.

### Version

vector 0.23.3 (x86_64-unknown-linux-gnu af8c9e1 2022-08-10)

**Comment by zamazan4ik** [comment]
Just a note that it is not strictly required, since some online FS grow is possible. So if Vector will implement such behaviour, the following use case will be discarded:

1. Run Vector on a volume with smaller free disk size than required
2. Resize volume to the size equal or greater than a sum of all required partitions

However, as a warning (with optin/optout promotion to an error) during an initial setup seems to be a nice feature and definitely will be useful.

**Comment by tobz** [comment]
I'm tackling this in #14455.

We're taking a more forceful approach by preventing Vector startup if the underlying disks are not theoretically large enough for all configured disk buffers to reach their maximum size.

Relying on operators to have to resize their storage after Vector has already started feels a bit too risky, and while operators will still be responsible for ensuring that other processes don't consume storage in a way that leads to the disk filling up, the least we can do is prevent Vector from running in scenarios where we know it has a greater-than-zero chance of encountering an error due to running out of storage.
