### ISSUE TITLE
Compile VRL to WASM (target: `wasm32-unknown-unknown`)

### ISSUE THREAD

**Issue by JeanMertz** [vectordotdev/vector#14653]
Compile the core VRL crate(s) to WASM, on the `wasm32-unknown-unknown` target (meaning, no access to WASI-backed OS-level capabilities).

The crates that need to compile, are:

- compiler
- core
- diagnostic
- parser

All of these should compile to `wasm32-unknown-unknown` without the need for hiding any code behind feature-flags.

**goals**

- [x] Add `CONTRIBURING.md` doc to `lib/vrl` with (for now) brief instructions on how to compile VRL to Wasm
- [x] Resolve any issues w.r.t. compiling VRL to Wasm
- [ ] Add CI step to compile VRL to Wasm, to ensure this keeps working moving forward (we will expand on this CI step in the future, to actually run VRL related tests)

**Comment by jonathanpv** [comment]
I have a question: for the second tick box to be ticked, does this mean resolving all the issues of the non wasm-functioning vrl methods? If not, then can I tick this check box. The check box in question is: 

 Resolve any issues w.r.t. compiling VRL to Wasm
 
 I'm assuming I will fix the issues first and then check it off though.

**Comment by JeanMertz** [comment]
This issue only tracks the VRL compiler compiling to Wasm. I could have been more clear on that. We're tracking the stdlib functions in #14654 and all the issues you created following your investigation there.

Since the compiler is already running in Wasm without issues, we can tick that box, for sure 👍

**Comment by jonathanpv** [comment]
The final tick box will likely be completed once the playground is auto deployed via netflify and CI since we would like to have  the latest vrl stdlib compiled with each commit update to ensure it still works. 

I believe this would be likely adding
`wasm-pack build --target web`
to the CI

then netlify commands to read the `/lib/vrl/web-playground` folder and begin hosting the single `index.html` page that reads from the generated `/pkg` folder from running the above command.
