### ISSUE TITLE
http_scrape support for HTTP methods (especially POST)

### ISSUE THREAD

**Issue by mans2singh** [vectordotdev/vector#14676]
### A note for the community

I have a use case where I want to use http request to get events from a server.  The server requires body based on which the it creates a response.  The http_scrape sink in 0.25 nightly does not have a `method` property so I cannot use it to make a POST request with a request body.

### Use Cases

I am trying to use [http_scrape](https://master.vector.dev/docs/reference/configuration/sources/http_scrape/) source which is currently in master branch.

I want to use http POST so that the http server can return a customized response (metrics/events) based on the body.
However, I did not find any configuration for http methods for http_scrape (like in the [http](https://master.vector.dev/docs/reference/configuration/sources/http) component). 

### Proposal

Feature request to support HTTP methods (specially POST) like [http](https://master.vector.dev/docs/reference/configuration/sources/http) source. 

### Version

0.25 nightly

**Comment by zamazan4ik** [comment]
@mans2singh Just to be clear - do you want to be able configure only HTTP method or also have an ability to set a custom HTTP body? Since `http` source does not have a way to set a custom body right now.

I guess provide an ability to use custom HTTP method even without an ability to specify a custom body would be still useful at least in cases when custom HTTP server implements only a specific HTTP method and cannot be reconfigured/extended. @spencergilbert what do you think?

**Comment by spencergilbert** [comment]
Yeah, I can see the value for configurable methods, and expect that body customization would also end up be valuable - worth another issue to track that specific feature.

**Comment by zamazan4ik** [comment]
@spencergilbert I think we should not close the issue - we still have no functionality to provide a HTTP request body. So, I guess you should reopen it.

**Comment by zamazan4ik** [comment]
Also I suggest discuss here, how we should implement providing a custom body to the HTTP request.

I suggest to add a custom `body` field to the config and then pass a content from this field as a raw HTTP request body without a parsing step (since a user can pass a body in any format - we cannot guess here).

The only check that could be done here - check, if a provided HTTP method with a `method` setting allows to specify a body. And if user provides `body` setting mistakenly - reject such a configuration during the start.

What do you think?

**Comment by spencergilbert** [comment]
Let's open a new issue for customizable `body` specifically 👍
