### ISSUE TITLE
Histogram metrics do not get sent to Datadog

### ISSUE THREAD

**Issue by derekhuizhang** [vectordotdev/vector#15390]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In Telegraf, if I configure a statsd input and Datadog output, when I sent a histogram metric to statsd, I get a bunch of gauges that are like `<metric namespace>.<metric name>.50percentile`,  `<metric namespace>.<metric name>.99percentile`, etc in Datadog.

In Vector, the aggregated_histogram type and distribution type with histogram statistic get sent as a distribution type to Datadog.

Instead, I would expect Vector to calculate buckets (0.25, 0.5, 0.95, 0.99, etc.) and send the buckets as gauges to Datadog, like in Telegraf.

### Configuration

```text
api:
      address: 0.0.0.0:8686
      enabled: true
      playground: false
    data_dir: /var/lib/vector
    sinks:
      datadog:
        default_api_key: <redacted>
        inputs:
        - aggregate
      prometheus:
        type: prometheus_remote_write
        inputs:
          - aggregate
        endpoint: <redacted>
        healthcheck:
          enabled: false
        tls: <redacted>
    sources:
      statsd:
        address: 0.0.0.0:8125
        mode: udp
        type: statsd
      internal:
        type: internal_metrics
    transforms:
      aggregate:
        inputs:
        - statsd
        - internal
        interval_ms: 10000
        type: aggregate
```

### Version

0.24.0

**Comment by tobz** [comment]
We explicitly made the choice in Vector to not do anything that resembles client-side percentile calculations. Doing client-side percentile calculations made sense back when projects like `statsd` first came on the scene, and there wasn't actually a better option, but things have changed a lot since then.

In particular, for the `datadog_metrics` sink, we have the ability to send full-fidelity sketches (via `DDSketch`) such that globally accurate percentiles can be created in Datadog without having to change anything on the Vector side. Practically speaking, we do recognize that enabling percentiles for distribution metrics does come with a cost, in terms of the number of custom metrics generated, although given that client-side percentiles would still lead to sending additional custom metrics for a given input distribution metric, the costs should generally be on par between the two approaches.

If you have a strong need to emulate the client-side percentile behavior, such that each Vector instance is calculating the percentiles like statsd or Telegraf would, you do have the option of using the `lua` transform to achieve this. The `lua` transform can hold state, which would allow you to replicate the typical behavior of aggregating metrics and then flushing the latest percentile calculates on an interval, and you have the full power of Lua to layer on any additional logic you may want or need.
