### ISSUE TITLE
Allow a flush of a batch to be issued to a sink

### ISSUE THREAD

**Issue by galenhwang** [vectordotdev/vector#15564]
### A note for the community

Original feature request in https://discord.com/channels/742820443487993987/1050732442211852299:

Use case is for issuing a flush of a batch. This is common for our use case where the source is a file (in our case, a log file).

Part of our config for the sink looks like (YAML format):
```
batch:
     # flush only every day
     timeout_secs: 86400
```
but sometimes we have a process that finishes modifying the file and we would want to do a final flush then. 

We would like to not wait on when the sink reaches the next `timeout_secs` interval for a flush to be issued. A hack we do currently is we restart Vector and reduce the batch timeout to a second to force a flush.

Related config is https://vector.dev/docs/reference/configuration/sinks/vector/#batch.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Force a flush of a batch to a sink. This can be when we don't want to depend on the timeout interval or the max event size.

### Attempted Solutions

Restart Vector and reduce the batch timeout to a second to force a flush.

### Proposal

Add change to Vector API/CLI to issue flush of the batch to a sink.
https://vector.dev/docs/reference/api/

**Comment by zamazan4ik** [comment]
@galenhwang Could you please explain, why your `timeout` period is so huge? Sounds strange to me and I am interested to hear about your use-case for that.

**Comment by zamazan4ik** [comment]
@jszwedko I think we could discuss here the way how to implement it. From my point of view, implementing it via API at first would be more beneficial since allows easier API-based integration with other services/control planes/scripts/etc.

Regarding API, I think we need here a simple API  with the only parameter like "Sink name/Sink names" to be flushed (since usually I do not want to flush all sinks).

What do you think?

**Comment by zamazan4ik** [comment]
@jszwedko Hmm, I doubt that restarting Vector is the right way to do the flush. I mean flushing the sinks during the shutdown is actually a good idea - totally agree with it.

But having a way to flush without a shutdown has its own scenarios, which cannot be done well with Vector restart:
* If I want to flush not all sinks, but only specified. If I need to restart a Vector - all sinks will be flushed.
* It increases Vector downtime. Imagine a scenario, when I want to flush a large number of events. So during the shutdown, Vector will not be able to process during the (possibly longer due to the long flush queue) amount of time. It, maybe, could be somehow mitigated by HA Vector setup, but not all people have HA Vector setup + I am not sure that it resolve the issue completely.
* Usually, you have some kind of alert for restarting services, e.g. to detect crashes or something like that. In this case extra restarts are not appreciated.
* Vector restarts (if they are not done via Vector API) are harder to integrate into the control plane compared to calling a restart Vector API via "usual" HTTP call.

In my opinion, we need to leave the open and seriously consider adding an explicit flush API to Vector API. What about priority for that? I do not, it's up to the Vector dev team.

**Comment by jszwedko** [comment]
Appreciate the thoughts!

> @jszwedko Hmm, I doubt that restarting Vector is the right way to do the flush. I mean flushing the sinks during the shutdown is actually a good idea - totally agree with it.
> 
> But having a way to flush without a shutdown has its own scenarios, which cannot be done well with Vector restart:
> 
> * If I want to flush not all sinks, but only specified. If I need to restart a Vector - all sinks will be flushed.

We did consider the fact that this would flush all of Vector rather than just one sink, but we figured this could be an acceptable compromise to still satisfy use-cases without adding a new, non-trival, feature to Vector's topology and API code which increases the overall maintenance burden.

> * It increases Vector downtime. Imagine a scenario, when I want to flush a large number of events. So during the shutdown, Vector will not be able to process during the (possibly longer due to the long flush queue) amount of time. It, maybe, could be somehow mitigated by HA Vector setup, but not all people have HA Vector setup + I am not sure that it resolve the issue completely.

In the use-case described above, I don't think HA is necessary since the input seems to be `file`s. If you have another concrete use-case I'm happy to see it though 😄 If you are using sources that receive input, deploying Vector behind a load balancer is our general recommendation as making Vector HA within itself isn't really an explicit project goal.

> * Usually, you have some kind of alert for restarting services, e.g. to detect crashes or something like that. In this case extra restarts are not appreciated.

Crashes can be distinguished by looking for a non-zero exit code.

> * Vector restarts (if they are not done via Vector API) are harder to integrate into the control plane compared to calling a restart Vector API via "usual" HTTP call.

That's fair, it does depend on however you are running Vector. The use-case above seems to want to trigger flushes locally so restarting would likely look like `systemctl restart vector`.

> In my opinion, we need to leave the open and seriously consider adding an explicit flush API to Vector API. What about priority for that? I do not, it's up to the Vector dev team.

The main issue is that this will add a decent amount of complexity to Vector's topology handling that we'd need to maintain indefinitely and consider with all cross-cutting features in the future. The value of the feature being added has to outweigh that and, in this case, I don't think that it meets that bar.

Again, the thoughts are appreciated. I'm happy to hear of more use-cases that could further motivate the value of this feature.

**Comment by zamazan4ik** [comment]
> The main issue is that this will add a decent amount of complexity to Vector's topology handling that we'd need to maintain indefinitely and consider with all cross-cutting features in the future. The value of the feature being added has to outweigh that and, in this case, I don't think that it meets that bar.

Yeah, I think this is the biggest issue here. Because implementation seems to be at least kind of tricky. And, FMPOV, Vector right now has more important to the users things to implement/polish.
