### ISSUE TITLE
`apache_metrics` enhanced tag support

### ISSUE THREAD

**Issue by DavidHuie** [vectordotdev/vector#15587]

**Comment by davidhuie-dd** [comment]
This source should be fine, but there is a big where there are duplicate keys in the metrics for `BusyWorkers` and `IdleWorkers`. One of the entries for each is related to async workers as per this bug report: https://bz.apache.org/bugzilla/show_bug.cgi?id=63300

Since we can't really differentiate them, there isn't much that we can do.
