### ISSUE TITLE
`Route` transform generates warning for unmatched events

### ISSUE THREAD

**Issue by amanmahajan26** [vectordotdev/vector#15865]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

While upgrading vector version from 0.20 to 0.26, I see that vector generates a warning for the `route` transform for `_unmatched` events.  Please see the logs below:

```
2023-01-09T12:30:34.455272Z  WARN vector::config::loading: Transform "router_output._unmatched" has no consumers
```

How to fix these warning message?

### Configuration

```text
[transforms.router_output]
type = "route"
inputs = ["application_logs"]

 [transforms.router_output.route]
 cloudwatch = 'includes!(.outputs, "cloudwatch")'
 s3 = 'includes!(.outputs, "s3")'
```

### Version

0.26.0

**Comment by jszwedko** [comment]
Hi @amanmahajan26 !

This change was part of adding an `_unmatched` route to consume events from the `route` transform that matched none of the defined routes. It can be ignored if you don't need to consume that route or you can wire it up to a `blackhole` sink. There are some upcoming improvements to the UX for component discarded events planned in https://github.com/vectordotdev/vector/pull/14708 including being able to mark that output as unneeded to suppress the warning.

I'll close this as intentional behavior, but feel free to leave any other thoughts or questions!

**Comment by amanmahajan26** [comment]
@jszwedko thanks for clarifying that. How can one configure a blackhole sink? If this is added in the documentation, that will be great.

**Comment by jszwedko** [comment]
Hey @amanmahajan26 !

This would look something like:

```
[transforms.router_output]
type = "route"
inputs = ["application_logs"]

 [transforms.router_output.route]
 cloudwatch = 'includes!(.outputs, "cloudwatch")'
 s3 = 'includes!(.outputs, "s3")'

[sinks.blackhole]
type = "blackhole"
inputs = ["router_output._unmatched]"
```

This would explicitly discard the unmatched events. The UX here is definitely a bit rough but we hope to improve it with https://github.com/vectordotdev/vector/pull/14708
