### ISSUE TITLE
Missing docs: Reference > Configuration > Global options needs doc on "enterprise" stanza for Datadog o11y pipelines

### ISSUE THREAD

**Issue by ngoldman-twilio** [vectordotdev/vector#16316]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Adding this stanza to our Vector configuration to enable Datadog observability pipelines:
```
enterprise:
  api_key: <redacted>
  configuration_key: <redacted>
  site: datadoghq.com
```

Results in this error:
```
ERROR vector::cli: Configuration error. error={"api_key":"<>,
"configuration_key":"<>","site":"datadoghq.com"} is not valid 
under any of the given schemas at instance path /enterprise
```

I'm working with Datadog support to debug it, but also looking into the Vector code for parsing this file, and noticed that this `enterprise` option isn't listed at https://vector.dev/docs/reference/configuration/global-options/

Would it make sense to add docs on how Vector reads/parses this `enterprise` block to the docs? Thank you!

### Version

vector 0.25.0 (x86_64-unknown-linux-musl b573b51 2022-11-01)

**Comment by jszwedko** [comment]
Hi @ngoldman-twilio !

I believe the version you are using had a bug with config parsing of the `enterprise` stanza. Can you try 0.25.2?

We are actually in the releasing a specific binary for Observability Pipelines so that option will be going away from Vector in the near future which is why it is undocumented. You can see https://docs.datadoghq.com/observability_pipelines/ for details about installing the new binary. If you have any questions about that, I'd encourage reaching out through the Datadog support channels (you can also see [this recent PM response](https://github.com/DataDog/helm-charts/issues/902#issuecomment-1416053230) for some more context).

**Comment by ngoldman-twilio** [comment]
Thanks @jszwedko ! **Upgrading to 0.25.2 fixed the problem** and the data is now flowing into datadog. And got it re: the docs makes sense, thanks again.
