### ISSUE TITLE
Datadog Observability Pipelines - Config not able to push when using "-config-dir"

### ISSUE THREAD

**Issue by StarpTech** [vectordotdev/vector#16413]
### Problem

According to the logs, the Datadog pipeline configuration can't be pushed.

```
2023-02-13T17:30:42.706 app[5eee41b9] sea [info] 2023-02-13T17:30:42.706340Z INFO vector::config::enterprise: Encountered retriable error. status=400 Bad Request

2023-02-13T17:30:42.706 app[5eee41b9] sea [info] 2023-02-13T17:30:42.706378Z INFO vector::config::enterprise: Retrying configuration reporting to Datadog Observability Pipelines in 16.333 seconds.
```

Not working: `"--config", "/etc/vector/vector.toml", "--config-dir", "/etc/vector/components", "--config-dir", "/etc/vector/shared-components"`

Works: `"--config", "/etc/vector/vector.toml"`

### Configuration

```text
[enterprise]
api_key = "${DD_API_KEY?Datadog api key must be supplied}"
configuration_key = "${DD_CONFIGURATION_KEY?Datadog config key must be supplied}"
site = "datadoghq.com"


# Rest is splitted in multiple files according to https://vector.dev/docs/reference/configuration/#automatic-namespacing
```

### Version

0.27.0 and 0.25.1

**Comment by jszwedko** [comment]
Hi @StarpTech !

Thanks for this report. Observability Pipelines has actually transitioned to a separate distribution (called the Observability Pipelines Worker). There are some docs around this here: https://docs.datadoghq.com/observability_pipelines/#what-is-observability-pipelines-and-the-observability-pipelines-worker. You can also see https://github.com/DataDog/helm-charts/issues/902#issuecomment-1416053230 for a recent clarification of the difference between this new distribution and Vector. Vector's support for reporting to Observability Pipelines will be removed in an upcoming release.

Bug reports and feature requests for Observability Pipelines should go through the [normal Datadog support channels](https://www.datadoghq.com/support/) so that they are tracked and routed to the correct parties. Do you mind opening this particular report there?

**Comment by StarpTech** [comment]
Hi @jszwedko, I understand your point, but closing an issue just because it's no longer in the focus of interest is a bit odd. It's still a bug though. We can't migrate so easily. Please reopen it.

**Comment by jszwedko** [comment]
> Hi @jszwedko, I understand your point, but closing an issue just because it's no longer in the focus of interest is a bit odd. It's still a bug though. We can't migrate so easily. Please reopen it.

Apologies, I'm realizing I could have been more clear 😅  I was closing the issue since we are removing the Datadog Observability Pipelines integration from Vector shortly and so there won't be any place to fix it in Vector itself. Instead, it would need to be addressed in the new Observability Pipelines distribution and feature requests / bug reports for that should go through the normal support Datadog channels.

Hopefully that is clearer but let me know if not 🙂

**Comment by StarpTech** [comment]
It is clear, but that's bad. Datadog sells the vector integration as "Observability Pipelines" and even helps with the integration, and now it is rejected :disappointed: Thank you.
