### ISSUE TITLE
healthcheck fails when multiple interlinked vector config files are used

### ISSUE THREAD

**Issue by AnuragEkkati** [vectordotdev/vector#16466]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

In our vector-agent deployment model we provide our standard agent.yaml and open up for teams to build their own custom-agent.yaml based on their specific prometheus scrape endpoints. 

Idea is the sink in the custom-agent.yml will be mapped to source endpoint in agent.yaml, which is opened only to support this customization. 

Provided the samples for better understanding

**command**
/usr/local/bin/vector/vector-agent -C /etc/vector/conf.d/ --color always --require-healthy true

**Files**
/etc/vector/conf.d/agent.yaml
/etc/vector/conf.d/custom-agent.yaml 

**Issue**:

When we start the agent with these config files in config directory, the healthcheck in custom-agent.yaml always fails. Maybe because the healthcheck is the first thing to execute, even before the source port is opened by the source config in agent.yaml. 

Can there be a retry option to enabled or made available so that it does't fail and exit the very first time it fails but retries ?

### Configuration

```text
custom-agent.yaml

data_dir: "/vector/custom/"
sources:
  prometheus_exporter:
    type: prometheus_scrape
    endpoints:
      - "http://localhost:9090/metrics"
    scrape_interval_secs: 120
    honor_labels: true
​
transforms:
  prometheus_exporter_transform:
    type: remap
    inputs:
        - prometheus_exporter
    source: |-
      .tags.job = "prometheus"
      .tags.instance_name = "test-instance"
sinks:
  local_sync_metric:
    type: vector
    inputs: [ "prometheus_exporter_transform" ]
    address: 127.0.0.1:7000
    healthcheck: true
    request:
      timeout_secs: 120
    version: "2"
    tls:
      enabled: false
      verify_certificate: false
      verify_hostname: false

agent.yaml

# Note: How to Run vector process
# /usr/bin/vector -C /etc/garuda/conf.d/ --color always --require-healthy true
​
data_dir: "/garuda/data/"
sources:
  grpc_metrics:
    address: 127.0.0.1:7000
    type: vector
    version: "2"
  grpc_logs:
    address: 127.0.0.1:7001
    type: vector
    version: "2"
  remote_write_metrics:
    type: prometheus_remote_write
    acknowledgements: true
    address: "127.0.0.1:7002"
  webhook_support:
    type: http
    address: '0.0.0.0:7003'
    acknowledgements: true
transforms:
...
...
sinks:
...
...
```

### Version

vector 0.21.1 (x86_64-unknown-linux-gnu 18787c0 2022-04-22)

### Debug Output

```text
Feb 16 01:44:10 vector-agent[92242]: 2023-02-16T01:44:10.934193Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Vector source unhealthy component_kind="sink" component_type="vector" component_id=local_sync_metric component_name=local_sync_metric
```

**Comment by fuchsnj** [comment]
Hey @AnuragEkka

Vector does not guarantee ordering of components, meaning the Vector sink can startup / run the healthcheck before the Vector source has started.

Since you are sending data back to the same Vector instance, I would recommend not using the `vector` source / sink and instead just wire up the components differently.

You can just have each custom agent contain a component with a standard name, such as `"custom_agent_output_1"`, `"custom_agent_output_2"`, .etc.

In the base `agent.yml` config, you can use [wildcard identifiers](https://vector.dev/highlights/2021-01-20-wildcard-identifiers/) to receive data from all custom agents by using an identifier such as `"custom_agent_output_*"`.
This should end up being more efficient since Vector doesn't need to send all of the data over TCP, and will remove the dependency on component ordering.

That being said, I do agree that healthchecks should probably retry, but I would prefer a separate issue be opened for just that.

**Comment by jszwedko** [comment]
For retrying health checks, we are going to repurpose https://github.com/vectordotdev/vector/issues/16578 to cover all health checks.

**Comment by jszwedko** [comment]
Closing this since we have https://github.com/vectordotdev/vector/issues/16578 to cover retrying health checks and otherwise I think the solution outlined in https://github.com/vectordotdev/vector/issues/16466#issuecomment-1470553605 should suffice for avoiding needing to wire up configurations in this manner. Feel free to reopen if you disagree though!
