### ISSUE TITLE
Test LavinMQ compatibility

### ISSUE THREAD

**Issue by zamazan4ik** [vectordotdev/vector#16574]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

CloudAMQP recently released a new AMQP-compatible broker - LavinMQ: https://www.cloudamqp.com/blog/lavinmq-is-now-hosted-at-cloudamqp.html, https://github.com/cloudamqp/lavinmq

We need to test, is it possible to integrate Vector with LavinMQ or not.

**Comment by zamazan4ik** [comment]
I have tested the simple workflow: connect to CloudAMQP-based LavinMQ and push a message via Vector - works fine. So I guess we could mention LavinMQ in the documentation near with RabbitMQ.

**Comment by jszwedko** [comment]
Thanks for testing! I think with protocols like AMQP 0.9.1 (or Syslog, or MQTT) we don't need to list every broker or service that supports the protocol since it is implied that if they do support the protocol, they work. If they don't work, there is a bug either in the broker or Vector in implementing the protocol.

I'll close this out, but again, thanks for verifying!
