### ISSUE TITLE
Add support for update/upsert mode in Elasticsearch sink 

### ISSUE THREAD

**Issue by adizalmanovich1** [vectordotdev/vector#16791]
A note for the community
Please vote on this issue by adding a 👍 [reaction] to the original issue to help the community and maintainers prioritize this request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Use Cases**
Background
As part of the auditing process, we write audit actions along with their status - which means that the first time the event action state will be written as pending, and at the end of the process the action will be **rewritten** with its success or failure status.
It will result in duplicate documents for each action, with a status of pending and a success/failure.

**Motivation**
update existing ES docs 

**Attempted Solutions**
add an option sink to Elasticsearch using update/upsert mode

**Comment by jszwedko** [comment]
Hi @adizalmanovich1 !

You should actually be able to achieve this in Vector already by setting the `_id` field on the event to a unique value. The default action is `index` which will update an existing doc if the `_id` matches rather than creating a new document.

I'll close this out, but let me know if that doesn't work for you and I can reopen.

**Comment by jszwedko** [comment]
Reference for `_id`: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html
