### ISSUE TITLE
Write application logs to stderr

### ISSUE THREAD

**Issue by anton-ryzhov** [vectordotdev/vector#1740]
Currently `vector` writes its logs to `stdout`.
That complicates pipeline debugging with console sink, because events are mixed up with application logs. Also it makes impossible to use `jq` for formatting and highlighting the output.

One possible workaround is to setup `target = "stderr"` for console sink and run it `vector 2>&1 1>/dev/null | jq .` — that is ugly.

**Comment by binarylogic** [comment]
Ah! That makes sense. I'd prefer to make this a CLI flag as well as a config setting. Ex:

```bash
vector --log-stream=stderr
```

and similar to #1709 

```toml
[observability]
log_stream = "stderr"
```

What do you think?

**Comment by anton-ryzhov** [comment]
In my experience apps usually logs to `stderr` and writes only "the output" to `stdout`. I don't know if is it stated somewhere, but I feel that it is a reasonable default.

I personally don't see any benefits of having that configurable to `stdout`. And `2>&1` standard trick could do that.

**Comment by binarylogic** [comment]
Hm, I could be wrong, but I always thought STDOUT was the default for any kind of running service. I'm curious what @lukesteensen and @a-rodin think.

**Comment by Jeffail** [comment]
I'd say for a service `stdout` is standard. However, for any tool that writes its results to `stdout` it's standard for its own logging (exclusively error messages usually) to be written to `stderr` for obvious reasons.

Vector can either be running like a service or a tool depending on your config, but primarily it is intended to be a service so I think `stdout` by default is reasonable. However, I think if we automatically switched to `stderr` when there's a `console` sink writing to `stdout` present then that would likely be appreciated by most users, and unlikely to aggravate any.

**Comment by anton-ryzhov** [comment]
Service can write all logs to stderr as well, don't see any problems with it.

Switching output by magic doesn't sound for me like expected behavior. Also console sink can write to stderr, so you shouldn't switch in this case.

**Comment by a-rodin** [comment]
I support the idea of setting the log output stream as a command line option. Moreover, I think we don't have restrict the log output stream to `stdout`/`stderr`, but can also support arbitrary output files.

**Comment by anton-ryzhov** [comment]
Or, all internal logs may be just another source. And user will decide to output it via `console` to out or err, or via `file`, or via `kafka`
Similar to https://github.com/timberio/vector/issues/68

**Comment by hhromic** [comment]
Hello, we just hit this same problem today :(
Consider me yet another user that expects application logging going to `stderr` and application data going to `stdout`.

According to Wikipedia about [standard streams](https://en.wikipedia.org/wiki/Standard_streams):

> Standard error is another output stream typically used by programs to output error messages or diagnostics. It is a stream independent of standard output and can be redirected separately. This solves the semi-predicate problem, allowing output and errors to be distinguished, and is analogous to a function returning a pair of values – see Semi-predicate problem: Multi valued return. The usual destination is the text terminal which started the program to provide the best chance of being seen even if standard output is redirected (so not readily observed). For example, output of a program in a pipeline is redirected to input of the next program, but errors from each program still go directly to the text terminal.

In *nix systems is specially important for applications to use this convention because it makes them very easy to pipe together and still all of their diagnostics remain visible. Vector currently breaks this, for example this is not possible:

```
$ cat /path/to/input | vector -c vector.yaml | jq > /path/to/output   # vector.yaml has a stdin source and console output
```

Moreover, in many systems `stderr` is **unbuffered**, which is specially important when an application crashes and the `stdout` stream (which is often **buffered**) doesn't get to be flushed yet. In this situation you miss important diagnostics logging that the application might have emitted before crashing.

In my humble opinion, I think Vector should consider making `stderr` the _default_ stream output for logging and diagnostics messages. This is how many many CLI tools work. If Vector is running as a service, logging to `stderr` is absolutely not a problem as most (if not all?) process managers support capturing from both streams.

**Comment by jszwedko** [comment]
These are good arguments, thanks @hhromic . Given those, and the discussion above, I think just always writing logs to stderr is appropriate.
