### ISSUE TITLE
roadmap page is not working

### ISSUE THREAD

**Issue by githubcdr** [vectordotdev/vector#17547]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

https://roadmap.vector.dev/ is not working

### Configuration

```text
github
```

### Version

0.30.0

**Comment by jszwedko** [comment]
Hi @githubcdr !

That page no longer exists. Did you find that linked somewhere?

We stopped maintaining that page because its accuracy was pretty poor given priorities are reset each quarter so we felt it was doing more harm than good.

I'll close this out, but let me know if you still found it linked anywhere.

**Comment by githubcdr** [comment]
Hi, it's on the readme.md in the root
