### ISSUE TITLE
How to get the original message ?

### ISSUE THREAD

**Issue by loveyang2012** [vectordotdev/vector#17840]
### Discussed in https://github.com/vectordotdev/vector/discussions/17831

<div type='discussions-op-text'>

<sup>Originally posted by **loveyang2012** July  1, 2023</sup>
The original message like this:
```
{
     "abilityState": "1",
     "t_servicename": "createTask",
     "tag": "push-openapi-access"
}
```
I  get message by vector like this:

```
{
"log": "{\"abilityState\":\"1\",\"t_servicename\":\"createTask\",\"tag\":\"push-openapi-access\"}"
}
```

this is my  transforms  config:

```
[sources.a]
    type = "fluent"
    address = "0.0.0.0:8225"
    receive_buffer_bytes = 65_536
[transforms.b]
type = "remap"
inputs = ["a"]
source = '''
  del(.host)
  del(.source_type)
  del(.timestamp)
  del(.tag)
'''
[sinks.out]
    inputs = ["b"]
    type = "console"
    encoding.codec = "json"
```
How can I get the original message ? 
I used to finish it by  transforms json_parser ,but now it has been deprecated.
```
[transforms.a_parse]
inputs = ["a_coming"]
type = "json_parser"
field = "log"
```</div>

please give me some ideas， please

**Comment by StephenWakely** [comment]
You need to use the [`parse_json`](https://deploy-preview-17198--vector-project.netlify.app/docs/reference/vrl/functions/#parse_json) remap function:


```coffee
. = parse_json!(.message)
```

This will set the entire event to be the parsed object - since you are deleting the metadata fields from the object already it looks like this is what you are after. 

If you just want to merge the object into the current event you can do something like (note `|=`):

```coffee
. |= parse_json!(.message)
```
