### ISSUE TITLE
Update/Upsert bulk mode for Elasticsearch sink

### ISSUE THREAD

**Issue by jlazic** [vectordotdev/vector#17852]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

Elasticsearch update API is described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html

What I plan on achieving with update API
1. Sending partial documents that are merged into single document in Elasticsearch
2. Eliminating duplicate documents in Elasticsearch

### Attempted Solutions

1. Tried both Reduce transform and merging multi-line logs with Lua. Neither of those worked because with distributed data stores like Kafka there are no guarantees on document ordering, nor we can be sure that single Vector node will always receive all documents that need to be merged
2. In case of network retries duplicated documents can be inserted into Elasticsearch. With update API and doc_as_upsert option there are strong guarantees that no duplicates would end up in Elasticsearch

### Proposal

Requires following ndjson format, where update request requires "doc" element added to json that will enclose our document. Similar with doc_as_upsert option.

Differences between plain update and doc_as_upsert as that in plain request only differences between original document and updated ones are sent. While in doc_as_upsert whole new document is sent, and Elasticsearch does the merging.

```
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field1" : "value1", "field2" : "value2"}, "doc_as_upsert" : true }

```

```
[sinks.es]
    type = "elasticsearch"
    inputs = [ "parser" ]
    endpoints = ["http://elasticsearch:9200"]
    mode = "bulk"
    id_key = "id"
    bulk.action = "update"
    bulk.doc_as_upsert = true
```

### Version

0.30

**Comment by blackrez** [comment]
Hello, any update on this issue ? I have the same needs about this feature.

**Comment by pront** [comment]
Continuing the discussion from https://github.com/vectordotdev/vector/discussions/21665#discussioncomment-11229424.

1. Here you will need to add the new `update` action: https://github.com/vectordotdev/vector/blob/a7acdfe19c7b913accb03a75260c616b841fe72a/src/sinks/elasticsearch/mod.rs#L112
2. This is the function that processes each logs because creating the service request: https://github.com/vectordotdev/vector/blob/a7acdfe19c7b913accb03a75260c616b841fe72a/src/sinks/elasticsearch/sink.rs#L109 You can add custom logic to transform the event to what the endpoint expects.
3. I think the most challenging part here is testing the complex interactions the original issue mentions (partial documents merging and duplicate elimination). For quick dev iterations, I would setup a local ElasticSearch instance and point my Vector config to it. Later these manual tests can be become actual integration tests. Existing ones are [here](https://github.com/vectordotdev/vector/blob/a7acdfe19c7b913accb03a75260c616b841fe72a/src/sinks/elasticsearch/integration_tests.rs).
