### ISSUE TITLE
Vector do not free file descriptors on large k8s cluster [duplicate]

### ISSUE THREAD

**Issue by alexandrtru** [vectordotdev/vector#18088]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello, team! Thanks for your work! 
We are very interesting use vector in large production in many k8s clusters, but we facing issue with open fd on our nodes. Issue seems same as [issue #17349](https://github.com/vectordotdev/vector/issues/17349) and [pull request #17603](https://github.com/vectordotdev/vector/pull/17603) trying to fix this, but both of them looks freezed. 

In our k8s installations logrotate rotate container logs every 10Mb, but some containers write logs very fast (like 50-100Mb in 30sec).  
Yeah, we know thats very bad, and we need to fix this. Those containers can be created randomly in our environment and we can't control creations of this right now - anyway we no need logs from this containers. 

I read issues abowe, and You answer that vector reads file to end, and after this check that file findable. But in our case in some reason vecrtor cant detect end of file (i think) and keeps file opened untill restarts. 

Metrics from devel cluster:
![image](https://github.com/vectordotdev/vector/assets/8166659/f5b9bccd-8181-488d-aaf5-f93ec67d5ca9)

How can i tune this behaviour? Some workaround maybe? Or misconfiguration?

Unfortinally ,we cant reconfigure our k8s clusters :(

### Configuration

```text
customConfig:
  api:
    enabled: true
    address: "127.0.0.1:8686"
  data_dir: /var/lib/vector
    #expire_metrics_secs: 0
  healthchecks:
    enabled: true
  sources:
    metrics_internal:
      type: internal_metrics
    kubernetes_pods_logs:
      type: kubernetes_logs
      #max_line_bytes:  10000
      glob_minimum_cooldown_ms: 10000
      ignore_older_secs: 10
      delay_deletion_ms: 10000
      read_from: "end"
      auto_partial_merge: true
        #extra_namespace_label_selector: 'logging=vector'
      namespace_annotation_fields:
        namespace_labels: ""
      node_annotation_fields:
        node_labels: ""
      pod_annotation_fields:
        pod_annotations: ""
  transforms:
    drop_empty_containers:
      type: filter
      inputs:
        - kubernetes_pods_logs
      condition: |-
        !(.kubernetes.container_name == null)
    drop_empty_message:
      type: filter
      inputs:
        - drop_empty_containers
      condition: |-
        !(strip_whitespace!(.message) == "") || !(.kubernetes.container_name == null)
    dedot_transform:
      type: remap
      inputs:
        - drop_empty_message
      source: |-
        . = map_keys(., recursive: true) -> |key| { replace(key, ".", "_") }
    route_events:
      type: route
      inputs:
        - dedot_transform
      route:
        vault_agent: |-
          match(.kubernetes.container_name, r'^vault.*$') ?? false
    vault_multiline:
      type: reduce
      inputs:
        - route_events.vault_agent
      group_by:
        - .kubernetes.pod_namespace
        - .kubernetes.pod_name
      starts_when:
        type: "vrl"
        source: is_timestamp(to_timestamp(split!(.message, " ")[0]) ?? false)
      merge_strategies:
        message: concat_newline
    processing_json_parse:
      type: remap
      drop_on_abort: true
      drop_on_error: true
      reroute_dropped: true
      inputs:
        - route_events._unmatched
        - vault_multiline
      source: |-
        parsed, parsed_err = parse_json(.message)
        cn = .kubernetes.container_name
        if  !match_any!(cn, [
                        r'^istio.*',
                        r'^jaeger.*',
                        r'^proxy-envoy$',
                        r'^mongodb.*$',
                        r'^vault.*$'
                   ]) { cn = "app" }
        if parsed_err == null && is_object(parsed) {
            . |= set!(., [cn], object!(parsed))
        } else {
            . |= set!(., [cn, "message"], .message)
        }

        del(.message)
  sinks:
    metrics_internal_sink:
      type: prometheus_exporter
      inputs:
        - metrics_internal
      address: "0.0.0.0:9598"
    opensearch_sink:
      type: elasticsearch
      inputs:
        - processing_json_parse
        - processing_json_parse.dropped
      api_version: "v7"
      auth:
        strategy: basic
        user: logstash
        password: "PASSWORD"
      mode: "data_stream"
      data_stream:
        type: |-
          {{ print "logstash-datastream" }}
        dataset: |-
          {{ print "k8s" }}
        namespace: |-
          {{ print "{{ .kubernetes.pod_namespace }}" }}
      bulk:
        index: |-
          {{ print "logstash-vector-k8s-{{ .kubernetes.pod_namespace }}" }}
      endpoints:
        [REDACTED]
      tls:
        verify_certificate: false
      request:
        timeout_secs: 10
        rate_limit_duration_secs: 2
        retry_initial_backoff_secs: 2
      batch:
        max_bytes: 5000000
```

### Version

0.31.0

### Additional Context

Vector installed as DaemonSet in cluster using Helm Chart 0.23.0

### References

[issue #17349](https://github.com/vectordotdev/vector/issues/17349) 
[pull request #17603](https://github.com/vectordotdev/vector/pull/17603)

**Comment by jszwedko** [comment]
Hi @alexandrtru !

The expected behavior is that Vector will keep the files open until they are deleted _and_ Vector has finished reading them. One guess is that Vector hasn't actually finished reading the files that were open but deleted. You could try increasing https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#max_read_bytes to see if it gives you better throughput. Some people have reported that it does.

**Comment by akutta** [comment]
@jszwedko  - I _think_ this is what's causing the issues:  https://github.com/vectordotdev/vector/commit/9a3881fad639bae889c87052fc5318586b17d9bb

Since Vector is reading files as oldest first, and we have a particular set of pods that are producing large volumes of logs (~8-10k/s vs the usual 1xx/s).  This is causing high log file rotations, but also meaning we only read the oldest file on each loop due to this code chunk:  https://github.com/vectordotdev/vector/blob/e104dc461130b47faeb91d27e486097202981361/lib/file-source/src/file_server.rs#L290-L292


We will likely try increasing the max_read_bytes to be able to read an entire file if necessary; which should _hopefully_ allow us to churn through the rest of the files more frequently and release the smaller logs much quicker.  On a particular node, we were holding ~460 GiB of log files handles with our daemonset.

As a nit - the documentation for max_read_bytes does not state anywhere that if that limit is reached, then it will NOT go on to the next file.  Perhaps we can make the oldest_first property configurable for the kubernetes_log source?

**Comment by jszwedko** [comment]
> As a nit - the documentation for max_read_bytes does not state anywhere that if that limit is reached, then it will NOT go on to the next file. Perhaps we can make the oldest_first property configurable for the kubernetes_log source?

The intention is that when that limit is hit that it _will_ go on to the next file but I see that that behavior is augmented when `oldest_first` is `true`. The intention with having `oldest_first` set to `true` is to try to finish reading older pod logs so that Vector can release the file handles but I can see how that might be suboptimal with the workload you described. I wonder if we could just expose the configuration option?

**Comment by akutta** [comment]
I think making it configurable with the current behaviour as the default would be appropriate

**Comment by jszwedko** [comment]
> I think making it configurable with the current behaviour as the default would be appropriate

👍 I opened https://github.com/vectordotdev/vector/pull/18376 to do that.

**Comment by alexandrtru** [comment]
Thanks! 

We are partially solved this issue in our environment, but sometimes (when logs event generates very fast) FD count growing as well.

We just setting up some filters and throttling events rules for our Vector's instances. This reduce burden (we send less events count to sink), but at the time we can loose some events.

I will wait merge of #18376 for testing, thanks!

**Comment by eddy1o2** [comment]
Hi @jszwedko , I could not find `oldest_first` option in [vector doc](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#oldest_first). Is the doc outdated?

**Comment by jszwedko** [comment]
> Hi @jszwedko , I could not find `oldest_first` option in [vector doc](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#oldest_first). Is the doc outdated?

Hi @eddy1o2 ! This hasn't been released yet. It'll be in 0.33.0 later this month.

**Comment by jszwedko** [comment]
You can run one of the nightly builds if you want to try it earlier though.
