### ISSUE TITLE
The interval option in demo_logs is broken since vector 0.28

### ISSUE THREAD

**Issue by fdhmcts** [vectordotdev/vector#18140]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

The interval option in demo_logs is broken since vector 0.28, and it is still broken in vector 0.31. It was still working in vector 0.27. The "interval" option in the "demo_logs" source seems to be rounded up or down to the nearest integer. We should be able to use decimal values such as "0.01" to control how often a new message is created. Now, it behaves as if we put an integer number. For example if we use "interval = 0.49" it will be rounded down to 0 and produce as many messages as possible. If we use "interval = 0.51" it will behave as if we had used "interval = 1" so it will wait one second.

### Configuration

```text
[sources.my_source_id]
type = "demo_logs"
format = "json"
interval = 0.1
```

### Version

0.31

**Comment by jszwedko** [comment]
Hi @fdhmcts !

This bug was actually discovered and fixed over here: https://github.com/vectordotdev/vector/pull/17917. It will be included in 0.32.0. Thanks for flagging! I didn't realize it was a regression; I was assuming the bug had always existed. I'll close this out, but let me know if you have any additional thoughts. To verify the fix works for you, you can try one of the Vector nightly builds (https://vector.dev/download/ -- switch to Nightly or the nightly Docker image builds: https://hub.docker.com/repository/docker/timberio/vector/tags?page=1&ordering=last_updated&name=nightly).
