### ISSUE TITLE
Warning is raised for `Maximum number of registrable allocation group IDs reached` even when `allocation-tracing` is off

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#18480]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

If you have more than 128 components in your configuration, Vector will issue the warning:

```
"Maximum number of registrable allocation group IDs reached (128). Allocations for component 'xxxxxxx_sink' will be attributed to the root allocation group.","target":"vector::internal_telemetry::allocations"}
```

This warning is only relevant if you are passing `allocation-tracing`. For normal usage, the allocation groups are not used.

The warning should only be raised when you want to trace allocations to prevent confusion.

### Configuration

```text
*a configuration with 129 components*
```

### Version

v0.32.1

**Comment by tobz** [comment]
The clincher here is that build allocation tracing _support_ by default, but we don't _enable_ it by default.

When support is compiled in, we always instrument component tasks with their own allocation group, even if it's not enabled and is functionally a no-op. We should be able to change that, though, so that it follows whether it's actually enabled at runtime.
