### ISSUE TITLE
Multiple files processing at same time

### ISSUE THREAD

**Issue by Manniac07** [vectordotdev/vector#18596]
Hopefully this is something easy to fix. I am reading files off a directory and have tried using both Prometheus exporter and Prometheus remote write to send my metrics to Victoria metrics. Everything works good until I send 3 or more files at the same time. In this scenario, I am only able to see metrics from 2 files values come across and  display in Grafana, I tried 6 files and only saw metrics for 3 files come across in Victoria Metrics.

**Comment by jszwedko** [comment]
Hi @Manniac07 !

If you mean to this to be a bug report, could you please reopen this with all of the relevant details requested by the bug report template so that we can investigate it?

If you don't mean it to be a bug report, this seems more appropriate as a GitHub Discussion. Could you open it there if this isn't a bug report?

Thanks!
