### ISSUE TITLE
Logs from `internal_logs` do not conform to log schema

### ISSUE THREAD

**Issue by guhcampos** [vectordotdev/vector#18626]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Consuming from `internal_logs` with `vector tap --outputs-of internal_logs` gives me events like this:

```
{
  "host": "vector-2",
  "message": "processing request",
  "metadata": {
    "kind": "event",
    "level": "INFO",
    "module_path": "warp::filters::trace::internal",
    "target": "warp::filters::trace"
  },
  "pid": 1,
  "source_type": "internal_logs",
  "timestamp": "2023-09-21T12:56:21.556802652Z",
  "vector": {
    "component_id": "datadog_agent",
    "component_kind": "source",
    "component_name": "datadog_agent",
    "component_type": "datadog_agent"
  }
}
```

Notice this isn't wrapped in a `log` dictionary, meaning it's not correctly interpreted by `log_to_metrics` for instance.

## Expected Behavior

Vector's `internal_logs` should conform to Vector's very own logging schema.

### Configuration

```text
---
customConfig:
  sources:
    datadog_agent:
      address: 0.0.0.0:8282
      type: datadog_agent
      multiple_outputs: true
    internal_metrics:
      type: internal_metrics
    internal_logs:
      type: internal_logs
```
```


### Version

vector 0.32.1

### Debug Output

_No response_

### Example Data

_No response_

### Additional Context

In this particular case, I'm trying to report the metrics affected by `tag_cardinality_limit` by parsing Vector's `DEBUG` logs (because Vector itself [does not tell me which metrics get dropped ](https://github.com/vectordotdev/vector/issues/17321), but the issue applies for every log level including `INFO` and `ERROR`.

### References

_No response_

**Comment by jszwedko** [comment]
Hi @guhcampos !

I think there might be a misunderstanding here. `log_to_metric` is meant to _derive_ metrics from logs. It doesn't make any assumptions about the incoming "schema" of the logs; it is all driven by configuration. In your case, you have configured the `log_to_metric` transform to look for a `metric_name` field in the log event, but there is none in the example event you provided.

I'll close this out since it isn't a bug, but if you want some help figuring out how to convert logs coming out of `internal_logs` into metrics feel free to open a GitHub Discussion instead. If you do, it'd be helpful if you can provide the input and desired output.
