### ISSUE TITLE
Upgrading Debian package to v0.33.0 overwrites configuration

### ISSUE THREAD

**Issue by osalmi** [vectordotdev/vector#18718]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Upgrading to or reinstalling Debian package version 0.33.0-1 silently overwrites `/etc/default/vector` and `/etc/vector/vector.yaml`.

To reproduce:
- Install Vector on Debian from the official [APT repo](https://vector.dev/docs/setup/installation/package-managers/apt/)
- Modify `/etc/default/vector` or `/etc/vector/vector.yaml`
- Reinstall Vector: `apt-get install --reinstall vector`
- The modified file is silently overwritten with the default content from the package

Encountered on both Debian 11 and 12 hosts.

### Version

vector 0.33.0 (x86_64-unknown-linux-gnu 89605fb 2023-09-27 14:18:24.180809939)

### References

- Maybe #18455

**Comment by jszwedko** [comment]
Thanks for this report @osalmi . I was able to reproduce this. The linked PR does seem suspicious though `dh_installdeb` claims it automatically handles files written to `/etc`. We'll aim to fix this for v0.33.1.

**Comment by koen-serry** [comment]
I believe this issue is still present in the latest Debian package.

**Version:** 0.57.0-1

Upgrading with:

```bash
sudo dpkg -i vector.deb
```

overwrote my locally modified `/etc/vector/vector.yaml`.

Inspecting the package shows that `vector.yaml` is no longer listed as a Debian conffile:

```text
$ cat control/conffiles
/etc/default/vector
/etc/vector/examples/docs_example.yaml
/etc/vector/examples/environment_variables.yaml
/etc/vector/examples/es_s3_hybrid.yaml
/etc/vector/examples/file_to_cloudwatch_metrics.yaml
/etc/vector/examples/file_to_prometheus.yaml
/etc/vector/examples/http_sink_custom_retry.yaml
/etc/vector/examples/prometheus_to_console.yaml
/etc/vector/examples/stdio.yaml
/etc/vector/examples/varint_framing_protobuf.yaml
/etc/vector/examples/wrapped_json.yaml
```

Since `/etc/vector/vector.yaml` is absent from `DEBIAN/conffiles`, `dpkg` treats it as a regular packaged file and replaces it during upgrades instead of preserving local modifications.

Unless this change was intentional, it looks like the package should add `/etc/vector/vector.yaml` back to `DEBIAN/conffiles`.

Also, it seems unusual that example configuration files are shipped under `/etc/vector/examples/`.

From a Debian filesystem hierarchy perspective, these files look more like documentation/examples and would normally belong under `/usr/share/doc/vector/examples/` (or `/usr/share/vector/examples/`), while `/etc/vector/` should contain only active administrator-managed configuration.

Currently the package marks the example files as conffiles but does not mark `/etc/vector/vector.yaml`, which is the file users are most likely to customize.

**Comment by pront** [comment]
Hi @koen-serry, this issue was closed 3y ago. Please create a [new bug report](https://github.com/vectordotdev/vector/issues/new?template=bug.yml).
