### ISSUE TITLE
s3 sink do not honor request retry config

### ISSUE THREAD

**Issue by anil-db** [vectordotdev/vector#19601]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

s3 sink do not honor request retry config because it uses default `should_retry_response` which is always success.

### Version

35.0

**Comment by jszwedko** [comment]
Could you provide some more detail on this one? `should_retry_response` just returns whether the request should be retried; it's not where the `request.retry` parameters are handled (e.g. if the maximum number of retries has been reached). Those are one level up.

**Comment by anil-db** [comment]
> Could you provide some more detail on this one? `should_retry_response` just returns whether the request should be retried; it's not where the `request.retry` parameters are handled (e.g. if the maximum number of retries has been reached). Those are one level up.

The point was that if `should_retry_response` will return `no need to retry because request was successful` irrespective of whether it was successful was not, no matter what value I set in `request.retry` it wont be retried.

as a block box user If I set this value `request.retry` to lets say 3 and I see my s3 request failing but no retry attempted from black box user perspective  `request.retry` was not honored.

**Comment by anil-db** [comment]
> > Could you provide some more detail on this one? `should_retry_response` just returns whether the request should be retried; it's not where the `request.retry` parameters are handled (e.g. if the maximum number of retries has been reached). Those are one level up.
> 
> The point was that if `should_retry_response` will return `no need to retry because request was successful` irrespective of whether it was successful was not, no matter what value I set in `request.retry` it wont be retried.
> 
> as a block box user If I set this value `request.retry` to lets say 3 and I see my s3 request failing but no retry attempted from black box user perspective `request.retry` was not honored.

i think `should_retry_response` default implementation should be based on `is_retriable_error` which is another abstract fn in same trait

**Comment by jszwedko** [comment]
Hmm, yeah, I see what you are saying. That is odd. We'll take a peek. It does look like an implementation of `should_retry_response` is missing (or the default implementation should be different).

**Comment by neuronull** [comment]
👋 hello

I think there might be some confusion around the usage of `should_retry_response`, as the documentation on it isn't super clear.

First let me ask- are you seeing request errors in the sink's processing, that are not retried? What is the behavior/ output from vector you are seeing which led to the inspecting of `should_retry_response`?

The trait function `should_retry_response` only comes into play when the service request was `Ok`. The purpose of the that function in the trait is to allow sinks extra logic to determine when to retry a request. For example in HTTP sinks, the http status code in the response may have been 200 , but for the service's protocol, it may actually be an error case.
A good example of this is the at https://github.com/vectordotdev/vector/blob/c2f32593776f1e9304dc20ae2adbfb3efb8a8eb8/src/sinks/elasticsearch/retry.rs#L97

Now, that isn't to say that some sinks could benefit from extending their logic by implementing this function. And it's possible that what you might be encountering with the `s3` sink is exactly this. To that end, it would be helpful to know more details about what log messages, debug output from Vector and behavior observed in `s3`.

I recorded the following sinks which implement `is_retriable_error` , but not `should_retry_response`. Note that `is_retriable_error` _does_ get evoked in the `Err` response from the service call. That is why it is the required trait function and `should_retry_response` is not required- because some sinks don't need that extra logic.

```
loki
aws_cloudwatch_metrics
azure
nats
datadog_metrics
datadog_logs
databend
aws_sqs / aws_sns
greptimedb
vector
aws_s3
```
