### ISSUE TITLE
Add rotate options for file sink

### ISSUE THREAD

**Issue by dani** [vectordotdev/vector#20492]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

When using the file sink, log files will grow indefinitely. We need to manage rotation with an external tool (like logrotate). It'd be conveniant to be able to handle rotation in vector (time based, size based, number of old logs to keep, compression)

**Comment by jszwedko** [comment]
Hi @dani ! Thanks for opening this. We'd previously discussed similar functionality in https://github.com/vectordotdev/vector/issues/2057 and came to the conclusion that Vector should just defer to, and work well with, external tools like `logrotate` rather than building in log rotation capabilities to Vector itself. Given that, I'll close this issue out, but let me know if there are use-cases you can think of that Vector could handle that something logrotate couldn't or if you have other reasons you think Vector should have this functionality.

**Comment by dani** [comment]
OK thanks. I tried to avoid logrotate (as it's often a pain to use. In my case, I can't even rely on it because of it's strange and hardcoded permission checks on log dir). Anyway, I worked around it with a naive copy + truncate + compress script based on size.

**Comment by toppk** [comment]
> OK thanks. I tried to avoid logrotate (as it's often a pain to use. In my case, I can't even rely on it because of it's strange and hardcoded permission checks on log dir). Anyway, I worked around it with a naive copy + truncate + compress script based on size.

@dani  is that script vrl? and something you can share?  I'm currently debating how to solve this, thinking of just writing a stdout capture for vector to do the file writing/rotating bits. like vector | filewriter.   basically inspired by multilog.

**Comment by dani** [comment]
No vrl, just a trivial, ugly [shell script](https://git.lapiole.org/nomad/monitoring/src/branch/master/templates/agent/rotate.sh).

**Comment by CDJ-happier** [comment]
> Hi [@dani](https://github.com/dani) ! Thanks for opening this. We'd previously discussed similar functionality in [#2057](https://github.com/vectordotdev/vector/issues/2057) and came to the conclusion that Vector should just defer to, and work well with, external tools like `logrotate` rather than building in log rotation capabilities to Vector itself. Given that, I'll close this issue out, but let me know if there are use-cases you can think of that Vector could handle that something logrotate couldn't or if you have other reasons you think Vector should have this functionality.

Hi, it seems that when using an external logrotate to rotate a file, the `copytruncate` option must be chosen (as the `create` option won't work—Vector will continue writing to the rotated file instead of the newly created file). This may lead to a potential risk of data loss. How can Vector handle this issue?
