### ISSUE TITLE
Vector sink load balance

### ISSUE THREAD

**Issue by evanzhang87** [vectordotdev/vector#20618]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

I want to send data from `vector` to `vector`, but I can only add one address in `vector` sink.

### Attempted Solutions

I tried `nginx` to do load balance, but it looks like it uses a long connection, when I restart sink `vector` server,the load will be unbalanced.
![image](https://github.com/vectordotdev/vector/assets/60881968/f6f1379d-dc0e-478c-a56d-bb00414d4268)
I need to restart source `vector` to rebalance.

**Comment by jszwedko** [comment]
Hi @evanzhang87 !

The `vector` sink is gRPC which is HTTP/2 over, as you noted, long-lived connections. I'd recommend using a load balancer that can handle balancing HTTP/2 traffic rather than balancing the TCP connections (i.e. Vector would create long lived connections to the load balancer which would create its own connections to the backends and balance HTTP/2 requests over them).

Separately there are a couple of related issues you may be interested in:

- https://github.com/vectordotdev/vector/issues/18249
- https://github.com/vectordotdev/vector/issues/19457

I think those issues cover this one so I'll close it, but let me know if you have questions!

**Comment by jszwedko** [comment]
For nginx you'd want to look at https://nginx.org/en/docs/http/ngx_http_v2_module.html
