### ISSUE TITLE
The Vector release binary is not stripped

### ISSUE THREAD

**Issue by ghost** [vectordotdev/vector#20707]
### Problem

The Vector release binaries that are installed by the installation script on x86_64 are not stripped. Stripping the binary by running 

```strip $(which vector)```

reduces the binary size tens of megabytes.

It would be good to add stripping of the Vector binary for release builds. I guess the best place to add it is the `Makefile`.

### Version

0.39.0

**Comment by jszwedko** [comment]
Hi @a-rodin !

Thanks for opening this! We discussed this before and don't want to strip symbols since it can make bug reports containing stack traces much less useful. For users that don't feel like they need this information, they can of course feel free to `strip`.

https://github.com/vectordotdev/vector/issues/20064 may also be of interest to you.

I'll close this out, but let me know if you have any additional thoughts or questions!
