### ISSUE TITLE
The computed value for`component_sent_event_bytes_total` metric in Sinks is taken before `encoding.except_fields`

### ISSUE THREAD

**Issue by neuronull** [vectordotdev/vector#20749]
If a user specifies the `except_fields` , all of those fields are included in the event bytes metric, which makes the reported value innacurate.

**Comment by StephenWakely** [comment]
[This PR](https://github.com/vectordotdev/vector/pull/17941) here attempted to make it so we took the counts after encoding.

But the count is done in the actual sink so you may find it's just the one sink you are looking at that is doing it incorrectly rather than it being a global problem. For example [here](https://github.com/vectordotdev/vector/blob/master/src/sinks/gcp_chronicle/chronicle_unstructured.rs#L369-L371) the byte_size is taken straight after transforming the event.

**Comment by jszwedko** [comment]
That matches my understanding too. @neuronull can you confirm which sink you found not publishing the metric correctly?

**Comment by jszwedko** [comment]
We followed up offline and verified that the sink that we thought wasn't reporting correctly, Datadog Logs, is in-fact doing so.
