### ISSUE TITLE
Automated release & recent posts mails

### ISSUE THREAD

**Issue by Hoverbear** [vectordotdev/vector#2076]
Replace our existing mailing list with a on-release triggered mail showing the recent changelog we already build for the website, as well as a summary of blog posts since last release.

**Comment by a-rodin** [comment]
If we implement this, I would love to have [canary](https://martinfowler.com/bliki/CanaryRelease.html) mails, so that the generated emails are sent automatically only to the core team members, and then sending the same email to all of the subscribers is triggered manually after verifying that the email looks right.

It might be especially useful because it is not possible to modify emails once they are sent, so we want to ensure that auto-generated emails actually looks good before all users see them.

**Comment by Hoverbear** [comment]
Agreed @a-rodin !

**Comment by jszwedko** [comment]
Closing since we don't have plans for this currently, but may revisit in the future.
