### ISSUE TITLE
Vector won't release file descriptor for deleted files, and those files will drain disk space

### ISSUE THREAD

**Issue by yankeguo** [vectordotdev/vector#21998]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

I'm currently utilizing Vector to collect the log files of Kubernetes containers. These log files have a date suffix appended when they rotate. After a certain period of time, these log files will be deleted.

However, Vector fails to close the file descriptors of those deleted log files. As a result, it will gradually consume disk space.

Moreover, it's quite difficult to locate them since these files have already been deleted. 

### Configuration

```text
"sources":
      "kubernetes_logs":
        "type": "kubernetes_logs"
```

### Version

0.42.0-distroless

**Comment by hgiasac** [comment]
@yankeguo AFAIK vector won't release file descriptors until EOF. Your log files may be too large to be read. 
You can try to configure the [rotate_wait_secs](https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/#rotate_wait_secs) setting. Vector will release the rotated files after X seconds.

**Comment by jszwedko** [comment]
@hgiasac is correct. Vector will only release the file handles once it has fully read the file to avoid missing data. As mentioned, you can use `rotate_wait_secs` to change this behavior to release the file after `n` seconds, even if it hasn't been fully read.

I'll close this since I think the behavior here is intended but let me know if have any other thoughts or questions!
