### ISSUE TITLE
Support indexer acknowledgements with `splunk_hec` sink

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#2374]
Apparently, when data is sent to a Splunk HEC it is not guaranteed to be saved if a 200 is received. To solve this Splunk implements an [indexer acknowledgment feature](https://docs.splunk.com/Documentation/Splunk/8.0.3/Data/AboutHECIDXAck). We should look into supporting within the `splunk_hec` sink.

**Comment by myndzi** [comment]
To be clear, the guarantee here is more like "if the system/service crashes, an indeterminate amount of data might have been lost", which is true of pretty much anything. However, the indexer acknowledgment feature here is a way for the Splunk server to report to the sender that data has made it completely through its own internals and been successfully written to disk. In practice (running around 80 indexers on AWS), we haven't observed significant instability though we have seen the occasional out-of-memory kill due to heavy searches.

**Comment by ctaintor** [comment]
Is it possible to just implement this feature as a "always return true?" As in - you return some random numbers and then when you receive random numbers, you say "yep, it was written!"

Personally I think the HEC indexer acknowledgement is a bad architectural idea but unfortunately the firehose implementation _requires_ it so I want to just accept the risk.

**Comment by ctaintor** [comment]
yes - let me comment there
