### ISSUE TITLE
Support for application/x-protobuf encoding in http sink

### ISSUE THREAD

**Issue by stuffandthings** [vectordotdev/vector#2726]
👋 

I'm wondering if it's possible to use the `http` sink to send `protobuf` payloads to an upstream server. FWIW, the server is **not** a gRPC backend. It's just a regular http api accepting **POST**s, but the messages are encoded as Protocol Buffers.

Thanks!

**Comment by lukesteensen** [comment]
Hi @stuffandthings! Protobuf is tricky because it's more of a way to specify formats than a format in itself. That really just means that we need a specific encoder/decoder for each type of protobuf message, as opposed to something like JSON.

We're currently working to support this through WASM. I would recommend watching #2367 to see when we have an implementation in place and documentation on how to use it.

That said, I'll leave this open to track any necessary integration with the HTTP sink.

**Comment by pablosichert** [comment]
https://github.com/vectordotdev/vector/issues/9744 could be relevant, even if it is for the source side of things. Will come back here once we have a solution for it.

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/9744
