### ISSUE TITLE
Kafka source Codec

### ISSUE THREAD

**Issue by SyluxDX** [vectordotdev/vector#2861]
In logstash the kafka input have the option to define the log's format as json
```
kafka {
  bootstrap_servers => 'bootstrap.kafka:9092'
  topics => ['events']
  client_id => 'events-shipper'
  group_id => 'events-shipper'
  codec => json
}
```
And to obtain the same result in vector is needed to configure the source and one transformation
```
[sources.kafka_in]
  type = "kafka"
  bootstrap_servers = "bootstrap.kafka:9092"
  group_id = "events-shipper"
  topics = ["events"]

[transforms.message_parser]
  type = "json_parser"
  inputs = ["kafka_in"]
  field = "message"
  drop_invalid = true
```

So I ask if its is possible to add  an encoding codec option?

**Comment by binarylogic** [comment]
Thanks @SyluxDX. I agree, there should be a simple way to decide data directly in the source. I've assigned this to @Hoverbear since she's worked in this domain within Vector.

@Hoverbear once you've finished your current projects I wanted to discuss a broader schema project (ref https://github.com/timberio/vector/pull/2428). And I'm wondering if this should be part of that, or if we should consider adding `decoding.codec` to sources?

**Comment by lukesteensen** [comment]
Another option we've discussed is making codecs a config-level idea that gets translated to source + transform in one phase of the compilation described in #2855.

**Comment by Hoverbear** [comment]
Noting we hit this in support chat today with user hreidar.

**Comment by jszwedko** [comment]
Closing since the `kafka` source does support configuring a `json` codec now.
