### ISSUE TITLE
Optimize `reduce` transform state flushes

### ISSUE THREAD

**Issue by lukesteensen** [vectordotdev/vector#3028]
In order to check for entries that have expired and need to be flushed, the implementation of the reduce transform in #2870 iterates over every merge state on every event it receives. This is obviously not ideal from a performance perspective and should be improved.

The simplest solution is likely to track expirations in a [`DelayQueue`](https://docs.rs/tokio/0.2.21/tokio/time/struct.DelayQueue.html) instead of the `ReduceState` and then add that stream of expirations to the `tokio::select!` loop.

**Comment by jszwedko** [comment]
Closing since our performance improvements are typically driven by performance analysis and this issue would be unlikely to be picked up without that motivation. I brought up the idea internally of just leaving a code comment for this sort of thing for us to find if we do go to optimize a particular area.
