### ISSUE TITLE
Stop vector after shipping files

### ISSUE THREAD

**Issue by P01s0nV** [vectordotdev/vector#3216]
Hey team.

I'm working on a project aimed to automate forensic artefacts harvest during incident response for different clients.

My goal here is to write a Python script that will be executed on a Windows machine and launch Vector to send multiple large csv files to a remote Elastic server. The issue here is that I need Vector to stop after it's done reading all files as I'm doing a one time harvest on a client's machine.

Did I miss an existing option or is the feature not implemented ?

**Comment by binarylogic** [comment]
Hey @P01s0nV, great question! We actually just shipped this feature for the `stdin` source ([highlight](https://vector.dev/highlights/2020-05-04-shutdown-vector-if-all-sources-finish/)), but I don't think this will work for the `file` source since it continually looks for new files. We could consider adding an option to the `file` source, but I'm curious if the `stdin` source would be sufficient for your use case?

**Comment by P01s0nV** [comment]
There is a possibillity that piping my files into `stdin` might not be a solution, as I trying to send large CSV files and have performance issues. I tried to benchmark that using `GetContent` in PowerShell, and it terminated with error:

> ERROR source{name=usn_in type=stdin}: vector::sources::stdin: error reading line: Lagged(4607)

I tried a few other methods as well, like using `Start-Process` in PowerShell or using redirection in cmd.exe, but could not make them work either.

**Comment by jszwedko** [comment]
Rolling into https://github.com/vectordotdev/vector/issues/11095
