### ISSUE TITLE
Vector not releasing file descriptors for rotated files

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#3440]
Copied from gitter https://gitter.im/timberio-vector/community?at=5f3172bcd28b99685e55795a

> Hi, I am running into an issue with vector that it's not closing file descriptors on rotation of files via logrotate (file source). These are nginx logs. This is is happening for already rotated *.access.log.1 files which are rotated a second time, to *.access.log.2.gz. These deleted file descriptors accumulate over a period of time and we have to restart vector to fix disk alerts. Fingerprinting is currently configured with checksum strategy, with file source configured to check only for *.access.log file.

Vector config:

```
[sources.nginx_access_logs]
type                  = "file"
include               = ["/mnt/log/nginx/*.access.log"]
glob_minimum_cooldown = 10000
max_line_bytes        = 102400
file_key              = "file"
host_key              = "hostname"
max_read_bytes        = 20480
oldest_first          = true
[sources.nginx_access_logs.fingerprinting]
fingerprint_bytes    = 256
ignored_header_bytes = 0
strategy             = "checksum"
```

logrotate config:

```
/mnt/log/nginx/*.log {
        size 1G
        missingok
        rotate 3
        compress
        delaycompress
        notifempty
        create 644 www-data adm
        sharedscripts
        postrotate
                [ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`
        endscript
}
```

**Comment by binarylogic** [comment]
Related https://github.com/timberio/vector/issues/763

**Comment by perfectayush** [comment]
I have discovered another issue which could be related to this. We didn't notice it so far, we have recently switched to vector from td-agent.

There are around 15 log files in the /mnt/log/nginx folder. 3 of our nginx logs are relatively high frequency, ~3000 lines per second combined (checked via tail -f and pv). Rest of them are around ~ 200 lines per second combined. 
I am using the lua transform and swimlane transform to bifurcate these logs into two lanes as follows.

```
[transforms.parsed_nginx_logs]
# General
type    = "lua"                     # required
inputs  = ["nginx_access_logs"]     # required
version = "2"                       # required

# Hooks
hooks.process = """
function (event, emit)
  high_frequency_log_files = {
                               ["/mnt/log/nginx/file1.access.log"]=true,
                               ["/mnt/log/nginx/file2.access.log"]=true,
                               ["/mnt/log/nginx/file3.access.log"]=true
                             }
  if high_frequency_log_files[event.log.file] then
     event.log.high_frequency = true
  else
     event.log.high_frequency = false
  end
  -- Very important! Emit the processed event.
  emit(event)
end
"""

[transforms.split_nginx_logs]
inputs = ["parsed_nginx_logs"]
type   = "swimlanes"

[transforms.split_nginx_logs.lanes.nginx_high_frequency_logs]
type                = "check_fields"
"high_frequency.eq" = true

[transforms.split_nginx_logs.lanes.nginx_low_frequency_logs]
type                 = "check_fields"
"high_frequency.neq" = true
```
We are further sending `nginx_low_frequency_logs` logs to s3 sink and a vector sink to an aggregator cluster. 
`nginx_high_frequency_logs` are sent to another s3 sink at another s3 prefix in same bucket.

We observed that our nginx_high_frequency_logs are not shipping in s3 and are flushed once in a while only from one  of the high frequency files file1.access.log, not others. 

I further investigated this by putting only the 3 high frequency files in the source config instead of `*.access.log` and noticed that at a single time, only one file is read and then source waits to read another file. This is very slow for us. I expected concurrent/multiplexed reads from each file. 

This could also be the reason that vector is never able to process these files and has these file descriptors open as it is never able to process the files due to logging frequency.  

Can you suggest a better approach here. The reason to use swimlane like this was to avoid writing multiple sources and transforms in a single configuration. 
1. Is there a backpressure somewhere which is slowing down reads probably due to any of
  1. lua transform 
  2. swimlane transform 
  3. aws_s3 sink
2. Is it better to process each of these high frequency files in different source or sink. I would have prefered to put all high frequency logs combined in a single s3 prefix and processed via single source?
3. Is there any tuning required in the `file` source or any other tuning. I had configured it with `max_read_bytes` to 20480. But I am observing in trace logs that byte reads are ~ 500 bytes.

Attaching full config for further inspection, it has 2 major source sink configuration. 1 for service clusters and 1 for nginx:
https://gist.github.com/perfectayush/1514ba958f571a781e79dd6f3fd5800b

**Comment by perfectayush** [comment]
I have made quite a few changes here to resolve issues on my side. Following are list of changes:
1. Change max_read_bytes to 2048 (default) everywhere, in file source.
2. Changed oldest_first = false everywhere. I suspected contention due to this. Files with low frequency logs will be prioritized always.
3. Removed buffer settings everywhere in all sinks. This switched buffer type from disk to memory.
4. Changed batch.max_bytes to 134217728 (128mb)

After making all these changes, cleaning up /var/lib/vector and restarting, I noticed that vector started consuming from all the files. The swimlane settings are still the same. Since vector was utilizing somewhat high CPU now, I switched the threads of the process to 2 with `-t 2` so as to not affect other processes on system. 

Additionally, I noticed that vector only started consuming after a few restarts, on some servers even after deleting files in /var/lib/vector, I had to restart a few times. My guess is that this is due to some initialization issue or due to some racing condition.  Not sure what the issue is here. 

We have a setting for vector where it restarts every 6 hours. Now I will observe tomorrow if these settings have fixed the things.

**Comment by perfectayush** [comment]
I can confirm now that vector was not releasing file descriptors because it was not processing those files. To solve the file descriptor issue, I had added following systemd config,
```
# /etc/systemd/system/vector.service.d/01-override-restart.conf
[Unit]
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
RestartForceExitStatus=0
RestartSec=1
# RuntimeMaxSec will kill service if it is running more than RuntimeMaxSec
# seconds with SIGTERM. RestartForceExitStatus setting above will restart
# the service
RuntimeMaxSec=21600
```

This would restart the service every 6 hours. Now I notice that servers on which vector is processing files, do not have `(deleted)` file descriptors after 4-5 hours, but servers where it is stuck have those `(deleted)` file descriptors.

I have also noticed that on some servers after restart, vector is not processing logs and is in some stuck state. I have observed this behaviour via `sudo perf trace -p $(pgrep vector)` as well, on servers where it is stuck, getting lot of quanta-upkeep calls, vector cpu util is ~ 0%:
```  2868.084 ( 0.001 ms): tokio-runtime-/12906 sched_yield(                                                          ) = 0
  2868.087 ( 0.001 ms): tokio-runtime-/12906 sched_yield(                                                          ) = 0
  2854.315 (50.066 ms): quanta-upkeep/12900  ... [continued]: nanosleep()) = 0
  2868.089 (36.298 ms): tokio-runtime-/12906 epoll_wait(epfd: 6<anon_inode:[eventpoll]>, events: 0x7f2d93496000, maxevents: 1024, timeout: 106) ...
  2904.387 (50.063 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  2868.089 (106.123 ms): tokio-runtime-/12906  ... [continued]: epoll_wait()) = 0
  2954.457 (19.768 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) ...
  2974.225 ( 0.003 ms): tokio-runtime-/12906 sched_yield(                                                          ) = 0
  2974.229 ( 0.001 ms): tokio-runtime-/12906 sched_yield(                                                          ) = 0
  2974.232 ( 0.001 ms): tokio-runtime-/12906 sched_yield(                                                          ) = 0
  2954.457 (50.060 ms): quanta-upkeep/12900  ... [continued]: nanosleep()) = 0
  2974.236 (30.288 ms): tokio-runtime-/12906 epoll_wait(epfd: 6<anon_inode:[eventpoll]>, events: 0x7f2d93496000, maxevents: 1024, timeout: 1920) ...
  3004.523 (50.062 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3054.593 (50.062 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3104.660 (50.061 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3154.728 (50.062 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3204.798 (50.061 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3254.866 (50.059 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3304.933 (50.062 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) = 0
  3355.002 (50.061 ms): quanta-upkeep/12900 nanosleep(rqtp: 0x7f2d926f9bb0, rmtp: 0x7f2d926f9bb0                  ) =0
```

On nodes where vector works, these quanta-upkeep calls are not there and vector cpu util is ~100% of a core. All calls there are related to tokio-runtime.

```
     1.160 ( 0.001 ms): tokio-runtime-/11827 epoll_wait(epfd: 6<anon_inode:[eventpoll]>, events: 0x7f0aed496000, maxevents: 1024) = 0
     1.164 ( 0.001 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.166 ( 0.001 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.169 ( 0.001 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.171 ( 0.052 ms): tokio-runtime-/11827 epoll_wait(epfd: 6<anon_inode:[eventpoll]>, events: 0x7f0aed496000, maxevents: 1024, timeout: 1316) = 1
     1.225 ( 0.002 ms): tokio-runtime-/11827 read(fd: 7<pipe:[3493938397]>, buf: 0x7f0ae7bf9440, count: 128        ) = 1
     1.229 ( 0.001 ms): tokio-runtime-/11827 read(fd: 7<pipe:[3493938397]>, buf: 0x7f0ae7bf9440, count: 128        ) = -1 EAGAIN Resource temporarily unavailable
     1.265 ( 0.002 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.269 ( 0.001 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.272 ( 0.002 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.275 ( 0.008 ms): tokio-runtime-/11827 epoll_wait(epfd: 6<anon_inode:[eventpoll]>, events: 0x7f0aed496000, maxevents: 1024) = 0
     1.389 ( 0.003 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.393 ( 0.002 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.396 ( 0.001 ms): tokio-runtime-/11827 sched_yield(                                                          ) = 0
     1.400 ( 0.001 ms): tokio-runtime-/11827 epoll_wait(epfd: 6<anon_inode:[eventpoll]>, events: 0x7f0aed496000, maxevents: 1024) = 0
``` 

I have also noticed that restarting again, fixes this issue on servers where vector is stuck. For now I am keeping the RuntimeMaxSec=21600 to restart vector every 6 hours.

**Comment by lukesteensen** [comment]
> I further investigated this by putting only the 3 high frequency files in the source config instead of `*.access.log` and noticed that at a single time, only one file is read and then source waits to read another file. This is very slow for us. I expected concurrent/multiplexed reads from each file.

As you figured out, this is due to you configuring the source with `oldest_first = true`. The purpose of that switch is to tell the source to finish reading files that were created first before moving on to newer files. The default behavior is to multiplex reads fairly across active files.

> This could also be the reason that vector is never able to process these files and has these file descriptors open as it is never able to process the files due to logging frequency.

This is likely the case. Since it is prioritizing the older files, it does not make progress on newer ones and the FDs are not freed until it has finished reading the files.

> Changed oldest_first = false everywhere

This _should_ be the only change you needed to make. The others seem totally fine but hopefully were not necessary to fix your issue.

> Additionally, I noticed that vector only started consuming after a few restarts, on some servers even after deleting files in /var/lib/vector, I had to restart a few times. My guess is that this is due to some initialization issue or due to some racing condition. Not sure what the issue is here.

If you started vector with a clean data directory, it should have started consuming files normally on the first try. Is it possible you cleared the directory while vector was still running and it rewrote the checkpoint files?

> I have also noticed that on some servers after restart, vector is not processing logs and is in some stuck state.

Do you have vector logs you could post from processes in this state? Enabling debug or trace level would be helpful. It sounds like something is getting backed up and the file source stops reading due to backpressure. This could be due to a problem upstream of a configured sink, etc. There should be some clues in vector's logs.

**Comment by jszwedko** [comment]
Closing since it seems like this was resolved, Vector was still processing the deleted files, but if anyone else runs into this issue, please leave a comment and we can re-open.

**Comment by akunafin** [comment]
I have the same issue that vector agent doesn't release the file descriptor after the log file has been rotated.
partial lsof output:
`
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-9rcjl-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-g5p8x-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-znc5l-phoenix-debug.log (deleted)
1	/usr/local/bin/vector	/var/log/clusterlogs/phoenix/kphoenix-7fbd46f4f4-g5p8x-phoenix-debug.log (deleted)
`

vector source config:
`
[sources.phoenix_source_debug]
  include = ["/var/log/clusterlogs/phoenix/*debug*.log"]
  type = "file"
  ignore_older = 10800
  [sources.phoenix_source_debug.multiline]
      start_pattern = '(INFO|DEBUG|WARN|ERROR|TRACE)'
      mode = "halt_before"
      condition_pattern = '(INFO|DEBUG|WARN|ERROR|TRACE)'
      timeout_ms = 1000
`
