### ISSUE TITLE
Optimize event processing at docker source

### ISSUE THREAD

**Issue by MOZGIII** [vectordotdev/vector#3647]
A follow up after #3607.

This issue is for tracking the refactoring outlined at https://github.com/timberio/vector/pull/3607#issue-474956630.

**Comment by jszwedko** [comment]
Closing since our performance improvements are typically driven by performance analysis and this issue would be unlikely to be picked up without that motivation. I brought up the idea internally of just leaving a code comment for this sort of thing for us to find if we do go to optimize a particular area.
