### ISSUE TITLE
Ability to chain parsing functions in the remap syntax

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3736]
Similar to #1477 and #2418, we need to allow for multiple parsing strategies in the Remap syntax, such as chaining regular expressions together until one passes.

Given the various ways users can parse data, and the related syntax changes, it's likely we'll need a spec. Let's start by proposing syntaxes here, if the discussion carries on we can move it to an RFC.

**Comment by FungusHumungus** [comment]
I can see three requirements that need to be filled here. These are my initial thoughts based on these..

1. Being able to specify a number of predicates - does this text match a regex, does this text contain a string, is this number within a given range and so on.
2. Being able to specify functionality to run when a predicate passes - control flow.
3. Extracting parts of the text with regexes.


## Predicates

I think just adding more functions largely covers the needed predicates. We already have numeric comparisons (`.foo > 4`), we need to add some text matching function (`matches(.foo, /a{3}/)`, `contains(.foo, "turnip")`, `starts_with(.foo, "turnip")`). The more the merrier!

## Control flow
In terms of control flow, we could just use `if...else...` statements:

```
if matches(.foo, /a{3}/) {
  dothis()
} else if matches(.foo, /b{3}/) {
  dothat() 
} else {
  domore()
} 
```

To make chaining multiple expressions more ergonomic we could introduce a switch statement. There's several variations I can think of.

The most basic switch, similar to most languages would choose the branch based on an exact match:

```
switch .foo {
  case "one": ...
  case "two": ...
  default: ...
}
```

I can't think of a reason why we couldn't expand that to regular expressions as well:

```
switch .foo {
  case /a{3}/: ...
  case /b{3}/: ...
  case "one": ...
  default: ...
}
```

Or, similar to SQLs CASE statement, we could make it so that if you do not specify an expression after the switch, then it evaluates each guard and runs the branch for the first one that returns true:

```
switch {
  case matches(.foo, /a{3}/): ...
  case matches(.foo, /b{3}/): ...
  case contains(.foo, "one"): ...
  default: ...
}
```

Potentially the most elegant, but also the most obscure and liable to generate support requests - we could make the variable you switch on become the first parameter of any function call in the case branch, thus allowing a full combination of function calls, regexes and exact matches:

```
switch .foo {
  case /a{3}/: ...
  case contains("one"): ...
  case "many": ...
  default: ...
}
```

## Regexes 

Pulling parts of the text out with a regex. We can have a function that runs the regex and returns the groups in an object:

```
  .matches = match("Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100", /^Started (?P<method>[^\s]*) for (?P<remote_addr>[^\s]*/)
  if .matches {
    // .matches is now {"method": "GET", "remote_addr": "127.0.0.1"}
  } else {
    .matches = match(".....")
    if .matches {
      ..
    }
  }
```

Control flow can be achieved with a number of nested if statements.

This could make for some cluttered and heavily indented code. It would be nicer if it could work with switch statements. One option could be to embrace the Perl way and populate the environment with the captures in a separate namespace - perhaps variables prepended with `$`. This is more succinct, but does add more obscurity to the scripts as the variables aren't explicitly declared anywhere. For short scripts, like remap scripts are liable to be, this may well not be a problem. Something like:

```
.line = "Started GET "/" for 127.0.0.1 at 2012-03-10 14:28:14 +0100"
switch .line {
  case /^Started (?P<method>[^\s]*) for (?P<remote_addr>[^\s]*)/: 
    .method = $method // "GET"
    .addr = $remote_addr // 127.0.0.1

  case ... :

  default: ...
}

```

**Comment by jamtur01** [comment]
@FungusHumungus Let's turn your comment above into the RFC for this and factor in thoughts around #2418.

**Comment by FungusHumungus** [comment]
Closing this in favour of #5382.
