### ISSUE TITLE
Move the remap language to a separate project

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#3784]
An idea I have is to move the remap syntax to a separate project. There are a few benefits to this:

- Increase visibility and usage of the language. If we're fortunate enough for this to catch on, it would help to reduce the learning curve with Vector, and might even help increase adoption.
- Help with maintaining the language.
- More clearly define the goals and boundaries of the language. Protecting it from Vector specific influence that would violate those goals.

**Comment by JeanMertz** [comment]
The `remap` transform will use `Vicscript` internally, I like that idea 👍

I would hold off until we're a bit further along with fleshing the language out though, as iterating on it goes a lot faster with the current situation, since all the testing infrastructure etc is already set-up.

Eventually though, it'd be nice to test the language in isolation, without having to build everything else Vector depends on.

**Comment by JeanMertz** [comment]
Just noting #4091 here, as moving this into a separate repo also means we'll want to remove the dependency on `event::Value` within the language. We're partially moving in that direction as we're adding support for non-`Value` types (such as `Regex`), but we're still relying on `Value` for all primitive types, for now.

**Comment by JeanMertz** [comment]
We agreed that this has become a "now or never" issue, as we're seeing more and more cross-referencing appearing between crates/projects. We also agreed that doing this will result in better encapsulation, and less API/design issues that we've seen creeping in.

Adding this to the workload for the current quarter.

**Comment by binarylogic** [comment]
I'm curious. How does this differ from a separate create in the `vector` repo? Shouldn't they be the same thing?

**Comment by lukesteensen** [comment]
I think we should talk through our goals a bit before we go ahead and do this. I understand that it's nice for VRL to be it's own thing, but part of the benefit of writing our own language is that it can be very tightly integrated with the rest of Vector.

The biggest draw of tight integration is avoiding any kind of FFI-like layer (or even sub-optimal trait interface) between remap and `event::Value`, but there's also a lot of benefit to directly sharing logic like `Lookup` and paths, etc. As we do more performance work I expect we'll want to tweak various representations and interfaces, and likely remove any extraneous layers that we can.

Even now with the language as a set of crates, we're not very tightly integrated (see the duplication and perf issues around `Lookup` vs paths) and I worry that if we separate the projects further we'll just be making it more difficult to capture those benefits in the future.

It's certainly possible to have our cake and eat it too, but I'm hesitant to prioritize somewhat nebulous concerns like encapsulation over things like simplicity and performance. I'll happily defer to those that work more directly on VRL, but I want to make sure we're not taking too narrow a view here and focusing on VRL itself vs the VRL + Vector system.

**Comment by JeanMertz** [comment]
While we're not committing to this yet, a few notes worth making since the last update:

- We now have a separate `value` crate that is shared across VRL and Vector, so there's no more conversion overhead going from one domain to the other.
- Likewise, we have a `lookup` crate that shares the path lookup API across both projects.
- We also now have Vector-specific VRL functions (such as for enrichment table lookups), but those are split out into their own `vector-vrl-functions` crate, so shouldn't cause any issues for his specific work.
- We have had _some_ amount of project-specific types crossing over the domain boundaries, so there's some clean-up work needed there, but nothing that will impact performance.
- The only integration point between Vector and VRL is still the `Target` trait, which has been reworked to have less overhead, and soak tests confirm this (i.e. performance is at above our goal currently).
- We do have a VRL test harness that pulls in the Vector Cue docs to test the VRL website, but the assumption would be that the VRL website would also be pulled out of the Vector repo, so all of that would also move over, and thus that test setup would continue to work as-is.
