### ISSUE TITLE
Ability to use `file` source in a batch-like manner

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#4271]
Mentioned in discord: https://discordapp.com/channels/742820443487993987/746070591097798688/761649096888942605

The user would like to run `vector` in a manner where it stops after it ingests all of a given set of files.

`remove_after` can help with determining when `vector` is done processing (the directory is empty), but for batch processing, it'd be easier if `vector` actually exited once it was done.

I feel like this has come up a few times before, but I couldn't find an issue for it.

**Comment by jszwedko** [comment]
This came up in discord: https://discord.com/channels/742820443487993987/746070591097798688/788404802530836490

**Comment by sach3000** [comment]
If possible, I will add my own use case for this issue.
We have our product (box version) and clients send us their logs for analysis (in case of errors). I want to analyze these logs to load into the ELK and that's it.
We want to run vector, have vector parse all the logs currently in our log files (assuming based on our previous setup) -> send them to sink(s) and then quit (rather than vector continually watching the files for additional data)

**Comment by jszwedko** [comment]
Closing in-lieu of https://github.com/vectordotdev/vector/issues/11095
