### ISSUE TITLE
New `redact_pii` Remap function

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#4519]
Ability to redact common personally identifiable information such as SSNs, etc. This should be a very basic, regex-based version.

## Prior Art

1. https://github.com/solvvy/redact-pii

## Example

```
redact_pii(., only_formats=["ssn", "phone_number", "credit_card_number", ...], except_formats=[...])
```

## Requirements

- [ ] Benchmark to get a sense of performance and if performance enhancements will be necessary.

**Comment by lukesteensen** [comment]
More prior art here: https://github.com/microsoft/presidio/tree/master/presidio-analyzer/presidio_analyzer/predefined_recognizers

**Comment by JeanMertz** [comment]
Some initial thoughts:

* We'll likely want to expand on the number of **pii redactors** as we go along, starting with a limit set of redactors.

	I realize the issue says "This should be a very basic, regex-based version.", but I would consider that an implementation detail for each individual redactor. We should choose whatever has the best performance (byte matching, string patterns, regex, etc).

* When redacting, I can see us exposing four **replace strategies** to replace pii data: `full`, `desciptive`, `partial`, and `custom`. E.g.:

	```rust
	$credit_card = "5555 5555 5555 4444"
	
	redact_pii($credit_card, redactors = ["credit_card"], replace_strategy = "full")
	// **********

	redact_pii($credit_card, redactors = ["credit_card"], replace_strategy = "descriptive")
	// CREDIT_CARD

	redact_pii($credit_card, redactors = ["credit_card"], replace_strategy = "partial")
	// **** **** **** 4444

	redact_pii($credit_card, redactors = ["credit_card"], replace_strategy = "custom", replace = "[REDACTED]")
	// [REDACTED]
	```

	The `partial` strategy is implemented for each redactor individually to be able to redact specifically for a given value. E.g:

	```rust
	5555 5555 5555 4444 	-> **** **** **** 4444
	john@doe.com 			-> j***@d**.com
	// etc
	```

	We can of course start with "full" to keep things simple.

* I would introduce **redactor groups** on top of individual redactors to make it easy to quickly redact groups of information:

	```rust
	"phone_number" => ["phone_number_us", "phone_number_nl", ...]
	"home_address" => ["home_address_us", ...]
	"all" 			=> ["phone_number", "home_address"]
	"strict" 		=> [...]
	"conservative" => [...]
	// etc
	```

	This will allow people to fine-tune as needed, but also to not overwhelm them with tons of supported redactors that have to be enabled/disabled individually.

	Again, this can be deferred until a future iteration, as long as we don't program ourselves out of this possibility.

* To be able to support use-cases we haven't built into a redactor, I would add a `pattern` redactor, which uses the `patterns` parameter to redact either the entire match if no capture groups are used, or redacts all matching capture groups. E.g.:

	```rust
	redact_pii($credit_card, redactors = ["pattern"], patterns = [/5+/])
	// **** **** **** 4444

	redact_pii($credit_card, redactors = ["pattern"], patterns = [/^(\d+) (?:\d+ )+(\d+)/])
	// **** 5555 5555 ****
	```

	The `patterns` parameter can also take a string, which combined with Vector's environment variable support in configurations, would make it easy to redact tokens, etc:

	_(I should note that I haven't investigated how we process environment variables yet, so this might need a bit of work to support)_

	```rust
	redact_pii(., redactors = ["pattern"], patterns = ["$STRIPE_TOKEN"])
	```

	_(we can either error at compile-time if the `pattern` redactor is enabled, but no pattern argument is provided, or we default to a `.*` pattern, i.e. matching everything)_

* Anything more complex that isn't supported natively through existing redactors, or is difficult to match using a regexp pattern can be redacted outside this function, using existing remap-lang primitives to match patterns, and replace those patterns with some redacted value. This is where functions such as `walk`, `replace`, `match`, etc. are of use.

---

Finally, there are a few blocking/optional features/functions we need to add before this function can be realized:

1. We need to support literal arrays in Remap. This is not a valid Remap script right now:

	```rust
	$foo = ["foo", "bar"]
	```

	_(I consider this a gap in the current grammar, so I'd love to add this regardless of what we do in this issue)_

2. To redact an entire event, we need to support traversing event fields. I'm almost done adding support for events to expose their tree of paths (e.g. `.`, `.foo`, `.foo[0]`, `.foo[0].bar`, ...) within remap, but the next step would be to have a language construct or function to traverse those paths and act on their values (see #4518)

3. If we want to alert at compile-time if an unknown redactor is provided (probably because of a typo, e.g: `redact_pii(., redactors = ["creditcar"])`), then we need to add support to provide arrays of enums (we support enums, but not arrays of enums) as parameter values. If we think runtime errors are enough, then this can be ignored.

**Comment by FungusHumungus** [comment]
Probably worth bearing in mind that not all credit card numbers are the same. Most are 16 digits long, but American Express can be 15 digits - there's a number of other variations [here](https://en.wikipedia.org/wiki/Payment_card_number).

**Comment by binarylogic** [comment]
@JeanMertz your proposal looks great, I'm 👍 .

**Comment by jamtur01** [comment]
Definitely like this proposal. Also +1 from me.

**Comment by lukesteensen** [comment]
See #1129 for some more context.

Overall this looks good to me, but I'd call them recognizers instead of redactors since their job is to recognize something that is then redacted according to some strategy. The function can probably also just be called `redact` or `sanitize` or something similar, since it's not necessarily specific to PII.

**Comment by jszwedko** [comment]
Re: redaction strategies, I might add hashing as a strategy. That way values can be collated.

**Comment by jszwedko** [comment]
Some discussion about handling of "filters" with configuration in https://github.com/timberio/vector/pull/5297#issuecomment-738635362

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/5297
