### ISSUE TITLE
New `replace_keys` Remap function

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#5377]
Blocked in #5785. The remap language has support for manipulating strings in event values, for example with the `replace` function. To do the equivalent with keys is not possible.

The use case is described in #3588, where keys containing dots can lead to broken indexing. A trivial solution would be to replace all dots with underscores, as is done by the `de_dot` filter in both Elasticsearch and Logstash. Better would be to support fully parameterized replacement just like the `replace` function does for values.

Suggested function: `replace_keys(map, regex | string, string, count = integer, depth = boolean) :: map`
Parameters are the same as for `replace` except for the first and the return type, both of which are maps instead of strings, and the additional `depth` options, which will cause it to recurse into maps and replace all their keys as well.

Usage for the scenario above would be something like:
`. = replace_keys(., ".", "_", depth = true)`

**Comment by jszwedko** [comment]
Related: https://github.com/timberio/vector/issues/4518

**Comment by binarylogic** [comment]
I'm curious if we want to accept a value as the first argument here? Whenever we use:

```js
. = ...
```

It is a flag to me that the function should operate on the entire event (like `del`). Otherwise, you could make the case that we should do:

```js
. = del(.key)
```

As a first step, I think it's simpler to just make this an event-level function:

```js
replace_keys('.', '_')
```

That example would replace _all_ keys on the event.
