### ISSUE TITLE
Consider only flagging top-level benches in CI

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#5901]
While taking a look at the lookup change PR #5374 I noted that a regression of 100% was flagged for the event benches: https://github.com/timberio/vector/runs/1659505315#step:17:21

```
create and insert single-level                                                                           1.1257 us  +71.826%     regressed
iterate all fields single-level                                                                          586.54 ns  +176.48%     regressed
create and insert nested-keys                                                                            2.3084 us  +109.19%     regressed
iterate all fields nested-keys                                                                           1.4575 us  +156.66%     regressed
create and insert array                                                                                  1.8922 us  +70.211%     regressed
iterate all fields array                                                                                 1.3352 us  +144.91%     regressed
```

We can see here, though, that the difference is typically on the order of a microsecond.

I then noted the topology benches didn't show a regression:

```
pipe/pipe_simple                                                                                         39.534 ms  +8.6301%     24.123 MiB/s    -7.9445%           none
pipe/pipe_small_lines                                                                                    29.874 ms  +15.726%     326.89 KiB/s    -13.589%           none
pipe/pipe_big_lines                                                                                      201.57 ms  -2.4051%     94.624 MiB/s    +2.4644%           none
pipe/pipe_multiple_writers                                                                               41.989 ms  +6.7692%     2.2712 MiB/s    -6.3401%           none
interconnected/interconnected                                                                            89.256 ms  -11.387%     21.370 MiB/s    +12.850%           none
transforms/transforms                                                                                    75.511 ms  +13.425%     13.893 MiB/s    -11.836%           none
complex/complex                                                                                          2.5898 s   +5.4730%     none
```

Which led me to the conclusion that the additional cost shown by the event benches wasn't a significant factor in the topology level benches which are more reflective of what a user might see.

This raised the question, echoed by @binarylogic, that maybe those low level benches aren't as useful when flagging in CI though would be useful for digging in to regressions actually observable at that level.

One relevant note is that the topology level benches seem to have a fairly high standard deviation which lowers the ability for criterion to notice smaller changes to the mean. This could compel us to still keep the finer grained benches that have less variance for noticing regressions sooner. I need to confirm this fact of high standard deviation, but it seems to be the case given means did show changes of +/-20% without the t-test showing a difference.

**Comment by bruceg** [comment]
> Which led me to the conclusion that the additional cost shown by the event benches wasn't a significant factor in the topology level benches which are more reflective of what a user might see.

I don't think we can necessarily conclude this. We only know that the topology level benchmarks we do run don't show the lower-level performance regressions. This could be because:
1. The low level regression don't matter overall. In this case, we should simply drop those low level benchmarks entirely.
2. The topology level benchmarks are too noisy to demonstrate the change within a confidence interval. You have already spent a lot of time to reduce that interval, and I'm not sure how much further we can push that.
3. The topology level benchmarks don't sufficiently model user experience. In this case we should look into enhancing them with more involved topologies that do actually stress the code paths involved in the regression.

I think we should be concerned about all performance regressions, no matter how low level. I have been following the performance work on the Rust compiler, and they have demonstrated that a series of tiny improvements *does* add up to overall significant improvements, even if each individual improvement may be lost in the noise. This means the opposite is also true — if we ignore the tiny regressions, they will add up over time and add up to overall significant regressions.

**Comment by jszwedko** [comment]
Notably the standard deviations weren't quite as large as I thought they were. The 95% confidence intervals for the topology benches:

```
pipe/pipe_simple               time:  [39.521  ms  39.534  ms  39.548  ms]
pipe/pipe_small_lines          time:  [29.862  ms  29.874  ms  29.885  ms]
pipe/pipe_big_lines            time:  [201.10  ms  201.57  ms  202.07  ms]
pipe/pipe_multiple_writers     time:  [41.957  ms  41.989  ms  42.023  ms]
interconnected/interconnected  time:  [84.610  ms  89.256  ms  93.880  ms]
transforms/transforms          time:  [75.478  ms  75.511  ms  75.544  ms]
complex/complex                time:  [2.5851  s   2.5898  s   2.5948  s]
```

**Comment by jszwedko** [comment]
Replaced by soak test framework.
