### ISSUE TITLE
Document special Kubernetes labels

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#6122]
I'm unsure if I'm representing this correctly, but to my knowledge, we support "special" labels that enable/disabled certain features. Ex:

https://github.com/timberio/vector/pull/6119/files#diff-87e733ba2fef5fa0570f9d719108e32abaab59b42f09c70cbd319be9a06ccc85R23

We should clearly document these so users know how they work.

@eeyun would you mind replying to this issue with all relevant details regarding these labels? Then we can work them into the docs.

## Open Questions

1. Is this specific to Helm or generic to k8s?
2. Should we provide examples on applying these labels?

**Comment by eeyun** [comment]
Right, so. These aren't Kubernetes labels as much as configurable values we expose in the Helm chart and those values really need to get documented.

The list is fairly straightforward since these things are already documented inline in the charts. We'll just need to get them all moved over to Cue data. 

Is there a specific spot or structure you'd like me to use to document this information?

**Comment by jszwedko** [comment]
Closing this since the documentation exists on the Helm charts now.
