### ISSUE TITLE
Create benchmarks for topology code

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6166]
Introduce mock source / sink components to bench just the topology code.

This will allow us to isolate the topology code to make improvements and flag regressions.

This will likely require some refactoring of the topology code to make it more benchable.

**Comment by MOZGIII** [comment]
I propose that we create a suite of utilities to facilitate the topology testing and benchmarking first.

## Topology testing

- mock source

  A source that is created with a tx channel, that simply passes data it gets on the channel into the topology.

- mock transform

  A transform that is created with two channels - an rx that returns events this transform receives, and a tx that can be used for emitting the events from the transform.

- mock sink

  A sink that is created with one rx channel - that returns all of the events from the topology.

The idea of having those three items is that we can avoid using things like sockets for simple topology testing once and for all. We'll also be able to implement more precise test flows using a lock-step mechanism to drive the topology - as we'll have precise control over each event's going in/out of the topology.

This is just the first step though, and the one that won't allow us to write tests to ensure the absence of races or data loss within for instance. I still think we'd have to take a deeper look into the topology itself and see if we can do something there.

## Topology benching

Similarly to the testing, we can introduce the source, transform and a sink to test the topology with, but unlike the test-flow oriented mocks, these ones will offer less control but do less internal synchronization. We'll also have to implement both of the transform kinds, as we'll have to compare the two.

Although the testing part is not directly related to the perf, but I think we should still cover is since we're at it. It is going to be a huge boost to the quality of life for the topology testing.

**Comment by jszwedko** [comment]
Closing since the component benchmark framework was replaced with the regression suite that does end-to-end benchmarks.
