### ISSUE TITLE
Allow loading remap scripts from files

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6403]
User request from discord: https://discord.com/channels/742820443487993987/764187584452493323/808744900921000046

Allowing loading of remap scripts from external files:

```
      [transforms.external]
      type = "remap" 
      inputs = ["X"]
      source = '''
        if (.message.Value == "Y")
        {
            #include "y.remap"
        }
        else
        {
            #include "z.remap"
        }
      '''  
```

It seems to me like this could be done at vector boot time if we only allow static filenames.

**Comment by JeanMertz** [comment]
> It seems to me like this could be done at vector boot time if we only allow static filenames.

I agree, there's no reason not to allow this.

Alternatively, people can already inject environment variables, so it's technically possible (although convoluted) to insert a VRL script from an external source.

**Comment by JeanMertz** [comment]
Not entirely. I kept it open because what I implemented is different from what's requested here.

That is, what we have now, is a way to load _one_ VRL source file directly in the `remap` transform. What this issue proposes is embedding one or more files into the top-level VRL source.

This requires more work because we have to figure out if Vector or VRL is responsible for loading those files, and if it's Vector, then we need to somehow parse the program before the VRL compiler sees it and embed external file sources.

If it's VRL, then we need to determine what the root path is, before loading additional files.

**Comment by JeanMertz** [comment]
I'll close this issue, as I don't think this is going anywhere anytime soon, or at all. We do allow loading VRL programs from external files, which covers most of what's requested here, and loading specific snippets inside programs can also be done through variable interpolation in the Vector config file, if needed.
