### ISSUE TITLE
Support indexer acknowledgements with `splunk_hec` source

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#6534]
Similar to supporting them in the sink: https://github.com/timberio/vector/issues/2374 we should support acknowledgements in the `splunk_hec` source too.

This seems to be required to use the Splunk endpoint for AWS Kinesis Firehose (https://docs.splunk.com/Documentation/AddOns/released/Firehose/RequestFirehose) and may also be required by other Splunk forwarders.

**Comment by ctaintor** [comment]
Just copying from another place. I might be wrong but I don't think there would be any real concept of "acknowledgement" in Vector since the entire point of it is to be able to split sources and sinks and you are thus likely to understand the times at which a log may not end up in the sink (and accept it).

So - if the above is correct then it feels like supporting indexer acknowledgement is as simple as just supporting the protocol. This would mean that when a request comes in that expects indexer acknowledgement:
* you return back a random id
* you support an ack endpoint that accepts these IDs and always returns "yep, I wrote that"

for us, this would solve the Kinesis Firehose issue and we would accept the risks that Vector may say that it received a log but it never showed up in the sink.

**Comment by ctaintor** [comment]
Also [here are the docs](https://docs.splunk.com/Documentation/Splunk/8.1.2/Data/AboutHECIDXAck) on how indexer acknowledgement works.

**Comment by ctaintor** [comment]
so
* token sent to `splunk_hec` needs to know if ack is requested or not (don't get me started on how asinine it is that this is a token setting, not a request)
* if token is enabled for ack, return back something like `{"ackID":"2"}`
• add a new endpoint to `splunk_hec` at `/services/collector/ack` that accepts an object with `ack` key and an array of IDs `{"acks":[0,1,2]}`
* that endpoint then just maps the request and returns an object like `{"acks": {"0": true, "1": true, "2": true}}` 

Of course if you're reading the examples you'll notice that the docs are likely wrong since some responses are strings and some are integers. who knows what is right

**Comment by ctaintor** [comment]
although now i realize we can just ditch Splunk HEC for firehose :)

(that said - maybe there are other reasons to support indexer ack)

**Comment by jszwedko** [comment]
Thanks for the thoughts @ctaintor !

You are correct that currently vector doesn't have any sort of mechanism to acknowledge that an event is anything other than accepted by the source, but there are some plans to improve that in #6517 which might allow for only acknowledging once the events have made it to the sink (or at least have been persisted to a file).

I agree, for now, we could support a dummy endpoint that doesn't do any validation simply for use with Splunk clients, like Firehose, that require it. An enhancement would be to augment the source to record the ids it generates so it can respond `true` for only ids it has actually generated. Later, we can link this feature with whatever we decide to do with #6517

**Comment by jszwedko** [comment]
Current thoughts here now that we have support for end-to-end acknowledgements in Vector:

We add support for the `acknowledgements = true|false` to the `splunk_hec` source:

* If `true` we only acknowledge messages that have been written out by associated sinks (or to the disk buffer if set)
* If `false` we acknowledge when the event has been written to the next component in the pipeline similar to what we do for the `kafka` source: https://github.com/timberio/vector/blob/21ddd7cd7cfaa0604c8e749ec9de787f7d56a62b/src/sources/kafka.rs#L213-L230
