### ISSUE TITLE
Propagate event metadata through the disk buffer

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7065]
The event metadata structure is not represented in the vector protocol, which means the metadata does not survive an event being serialized to the buffer and then deserialized. The protocol needs to be enhanced to add support for the metadata, and the disk buffer needs to use this support to handle metadata. However, the `vector` source and sink also use the same protocol definition, and the metadata should *not* be transmitted over this protocol, so care will need to be taken that this actually happens.

**Comment by bruceg** [comment]
Note that this is required to support end-to-end acknowledgements after events have been buffered.

**Comment by bruceg** [comment]
I would prefer to close this and ignore this idea. The only reason this is here is that this behavior was requested at the start of the end-to-end-acking project. I still think it is possible, as the behavior is independent of the disk buffer low-level mechanism, but I agree it is probably not desirable.

@binarylogic ISTR you originally pushed for this to be made possible, your thoughts?

**Comment by jszwedko** [comment]
I stumbled back across this today. I agree with not persisting event finalizers, but I do think we need a way to persist the `datadog_api_key` metadata that was added in #7394 as otherwise this prohibits the use of disk buffers if using the pass-thru ability of `datadog_agent` -> `datadog_logs` to re-use the same API key the Agent sent the logs with.

I think we _would_ want to pass along that key with `vector` -> `vector` communication.

cc/ @binarylogic just for context that this isn't currently possible.

**Comment by binarylogic** [comment]
IMO, buffers should be transparent, regardless of the medium. Therefore, event metadata should be persisted by default. In the case of security I have a few thoughts:

1. This should be clearly documented.
2. Users should be encouraged to encrypt their disk.
3. We could consider flagging sensitive metadata values as such and encrypting those values directly.

I like 3, since we shouldn't offer insecure defaults, but we'll need to discuss performance implications, etc.

**Comment by jszwedko** [comment]
👍 Agreed on all points.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/14264 . For event finalizers, that control acknowledgements, we've decided to mark events as acknowledged once they hit the disk.
