### ISSUE TITLE
Tap should support inputs as well as outputs

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#7116]
Currently, Vector's `tap` API / CLI subcommand supports "outputs" -- events that flow _from_ a component, rather than _into_.

We should also support inputs. The use-case would be bidirectional observability into transforms (which have both inputs and outputs) and sinks (which only receive inputs.)

**Comment by jszwedko** [comment]
I chatted with Will a bit about this earlier. He suggested the interface use CLI flags for specifying whether to tap inputs or outputs. I think this could look something like:

```
vector tap --inputs foo --inputs bar --outputs baz
```

To tap specify whether to tap the input or output of a component. We can maintain the CLI arguments to tap outputs for compatibility.

I initially wasn't crazy about using flags for this because they are pseudo-required parameters, but the fact that `vector tap` doesn't require any arguments makes me think it would be ok. An alternative might be something like:

```
vector tap inputs:foo inputs:bar outputs:baz
```

Where the arguments have additional metadata encoded in them.

**Comment by leebenson** [comment]
Given that tap only supports outputs right now, I'd propose the following:

- Absent a flag, the component defaults to output only.
- With `--input <component>`, it's input only.
- With `--all <component>`, it's both.

Example:

```
vector tap --all id1 --input id2 id3
```

Would mean:

- `id1` returns both.
- `id2` gives inputs.
- `id3` gives outputs.

And:

```
vector --all
```

... gives everything, for all components.

Practically, I can see value in mixing when #6898 lands, and it's clear the origin. Otherwise, mixed outputs part of the same stream are likely to be confusing.
