### ISSUE TITLE
InfluxDB Logs Sink, add options to exclude _measurement postfix and metric_type tag

### ISSUE THREAD

**Issue by uqix** [vectordotdev/vector#7183]
InfluxDB Logs Sink, add options to exclude `_measurement` postfix `.vector` and `metric_type` tag.

![image](https://user-images.githubusercontent.com/10142314/115378952-a7dfdd80-a203-11eb-8feb-9a617e322cce.png)

Image from [doc](https://vector.dev/docs/reference/configuration/sinks/influxdb_logs/#mapping-example)

**Comment by jszwedko** [comment]
Hi @uqix ! Could you provide an example of what you'd like the line to be mapped to?

It seems like you want it to look like:

```
host=my.host.com custom_field="custom_value",message="<13>Feb 13 20:07:26 74794bfb6795 root[8539]: i am foobar" 1572642947000000000

```

?

**Comment by uqix** [comment]
It seems that the measurement name is < namespace>.vector, is this  . vector hard coded?

**Comment by jszwedko** [comment]
Yeah, it does appear to be. I'm not super familiar with InfluxDB, but this does seem a bit odd.

https://github.com/timberio/vector/blob/b25e0cb3a74da87d205b7673dedda2fdeac1307a/src/sinks/influxdb/logs.rs#L165-L170

The format is indeed `<namespace>.vector` where `vector`, I believe, would be the measurement name. It appears to have been that way since the sink was introduced in https://github.com/timberio/vector/pull/2474

We'll need to look into this more. Thanks for reporting!

**Comment by juvenn** [comment]
@uqix FYI, as long as #10217  is released, you can use `encoding.except_fields=["metric_type"]` to exclude it. Also you can specify any measurement you like, e.g.

```toml
[sinks.influx]
type = "influxdb_logs"
measurement = "my_measure"
encoding.except_fields = ["metric_type"]
```
