### ISSUE TITLE
Add build and version data to internal metrics

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#7364]
Vector embeds data about the build time and release version into the binary using the `built` crate, exposed in `crate::built_info`, and logs some of this at program startup. For monitoring a fleet of vector agents, however, it would be useful to have visibility on these through metrics that could be pulled into monitoring tools.

Suggested metrics:
* `vector_info`: a gauge, with a fixed value of `1`, that has information about build version etc as labels.
* `rust_info`: a gauge as above with labels indicating the version of Rust used to build this version (ref Prometheus which exposes similar for the Go environment used to build it).
* `build_age`: a gauge (counter?) exposing how long ago this release was built.

Note that some of these require re-emitting the metrics on regular intervals, and so may require an additional background task to recalculate them.

**Comment by binarylogic** [comment]
I would like to see these added to the [instrumentation spec](https://github.com/vectordotdev/vector/blob/master/docs/specs/instrumentation.md) so we could build consensus around how these are collected and reported.

cc @leebenson since I assume this is required to drive some of the UI feature?

**Comment by hhromic** [comment]
I was just about to open a feature request for this.

In Prometheus, this problem is very easily solved using the defacto-standard `build_info` metric:
https://www.robustperception.io/exposing-the-software-version-to-prometheus

This can be name-spaced for Vector itself (`vector_build_info`) or Rust (`rust_build_info`) in the same way as orginally described in this issue by Bruce and the link I shared above.

I'm implementing this same metric for our internal software and it is _very_ useful to track outdated instances in large deployments. Vector is becoming more and more used in our infrastructure and having a way to easily track the deployed version numbers is very valuable to know what needs updating.

Hope it gets considered for the short term future! :)
