### ISSUE TITLE
Add buffer to the socket source 

### ISSUE THREAD

**Issue by valerypetrov** [vectordotdev/vector#7510]
Hi there, it would be convenient to add the buffering feature for the socket source. Because the TCP senders may send a huge amount of data(or it could spike) and in the case of laggy elasticsearch it would nice to have a buffer.

@jszwedko

**Comment by ethinx** [comment]
I did a test and topoloy as follows:

(sender [sources.generator] -> [sinks.socket.tcp] ) ===> (receiver [sources.socket.tcp] -> [sinks.file] )

With prometheus monitor, it seems that the maximum input events is about 40k/s even though I started more sender. Moreover, the Recv-Q of receiver socket seems full like:

State      Recv-Q Send-Q        Local Address:Port          Peer Address:Port
ESTAB      4336803 0                 127.0.0.1:19000            127.0.0.1:50276
ESTAB      4391174 0                 127.0.0.1:19000            127.0.0.1:50214

Is this situation about tcp buffer? Wondering if there is a way to increase the thoughput? Allow receiver fetch events as fast as possible.

**Comment by jszwedko** [comment]
> With prometheus monitor, it seems that the maximum input events is about 40k/s even though I started more sender. Moreover, the Recv-Q of receiver socket seems full like:

What do you mean by starting more senders? Do you mean more vector instances with `socket` sinks?

**Comment by ethinx** [comment]
@jszwedko yes.

I did test again, I started a vector as receiver, with two socket.tcp source on two port (30010, 38010), then started two vector instances, one sent to 30010, one sent to 38010.

1. Two senders sent to two sources accordingly, receiver handle 38k/s events

![two-sinks](https://user-images.githubusercontent.com/965612/123509050-ea131880-d6a5-11eb-94fb-6a578b03cf71.png)

2. Stop one sender, it means only one source of receiver responsible for input events, the throughput not changed

![1-sinks](https://user-images.githubusercontent.com/965612/123509055-f13a2680-d6a5-11eb-8810-796146353252.png)

I think our focus point are similar, about the throughput.

From the metrics above, it seems that in vector, same kind of sources share a same buffer, rather than start different thread/process to handle input events. Increase the amount of source help nothing?

Could we hole/handle as many as events with affordable resource, like memory or disk buffer.

**Comment by jszwedko** [comment]
Hi @ethankhall ,

Thanks for the additional details! What you show there seems to be what I would expect. When you had two senders and two sources, you saw 19k messages / second per source for a total of 38k messages / second . When you removed one of them, the other source went to 35.4k / second which is just under what it maxed out at before.

My guess is that the `file` sink is the bottleneck here; that it can't write any faster than ~40k messages / second in your setup so no matter how many `socket` sources you add, the cumulative messages / second will never exceed that as backpressure from that sink will flow back to all associated sources. The `file` sink runs as a single task that will consume events from all incoming sources. Does that make sense? You _may_ be able to improve throughput by having one `file` sink per `socket` source.

**Comment by jszwedko** [comment]
Closing this based on https://github.com/vectordotdev/vector/issues/7510#issuecomment-870059235
