### ISSUE TITLE
VRL error `can't apply an OR to these types` on mixed `match!` expression

### ISSUE THREAD

**Issue by leebenson** [vectordotdev/vector#7813]
This fails:

```
$ (.foo == "this" || match!(.bar, r''))
can't apply an OR to these types
```

Possibly related -- coalescing when `match` with equality checks also fails:

```
$ (.foo == "this" || match(.bar, r'')) ?? false

error[E651]: unnecessary error coalescing operation
  ┌─ :1:1
  │
1 │ (.foo == "this" || match(.bar, r'')) ?? false
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ -- ----- this expression never resolves
  │ │                                    │
  │ │                                    remove this error coalescing operation
  │ this expression can't fail
```

But sticking to just _match_ doesn't:

```
$ (match(.foo, r'') || match(.bar, r'')) ?? false
false
```

Range expressions are also fine:

```
$ (.a > 5 || match(.bar, r'')) ?? false
false
```

**Comment by leebenson** [comment]
cc @JeanMertz @StephenWakely

**Comment by JeanMertz** [comment]
I haven't looked too deep into this yet, but regarding this error:

```
$ (.foo == "this" || match!(.bar, r''))
can't apply an OR to these types
```

That error seems to be a bit misleading, as it indicates that the rhs expression being resolved failed at runtime, it has nothing to do with "types":

https://github.com/timberio/vector/blob/8bb5ec4ddd0b560a18569b0a7907bb6ab4eb177a/lib/vrl/compiler/src/value/arithmetic.rs#L78-L94

In this case, my assumption is that `.bar` isn't a string, and thus `match!` fails, which then fails the `||` operation, which results in the (incorrectly labeled) "can't apply an OR to these types" error.

This is backed up by trying it in the REPL:

```coffee
$ (.foo == "this" || match!(.bar, r''))
can't apply an OR to these types

$ .bar
null

$ .bar = "baz"
"baz"

$ (.foo == "this" || match!(.bar, r''))

error[E620]: can't abort infallible function
  ┌─ :1:20
  │
1 │ (.foo == "this" || match!(.bar, r''))
  │                    ^^^^^- remove this abort-instruction
  │                    │
  │                    this function can't fail
  │
  = see documentation about error handling at https://errors.vrl.dev/#handling
  = see language documentation at https://vrl.dev

$ (.foo == "this" || match(.bar, r''))
true
```

---

The second error you mentioned:

```
(.foo == "this" || match(.bar, r'')) ?? false

error[E651]: unnecessary error coalescing operation
```

I _believe_ there's an issue in the type definition here:

https://github.com/timberio/vector/blob/8bb5ec4ddd0b560a18569b0a7907bb6ab4eb177a/lib/vrl/compiler/src/expression/op.rs#L132-L145

That is to say, the second or-arm defines:

```rust
Or if !lhs_kind.contains(K::Null) => lhs_def
```

This seems to be inaccurate, since even if the lhs isn't null, it can still be `false` at runtime, and so we need to merge the rhs type def here.

We've had a number of bugs in this logic specifically, so it's good to get another set of eyes on this (and expand our test cases here), cc @StephenWakely.

**Comment by leebenson** [comment]
Thanks for looking, @JeanMertz.

Makes sense re: the `!` runtime failure. We're not using the `!` override in Datadog -> VRL translation, so this doesn't directly apply to the current use-case; it was just a convenient example to illustrate the error. It sounds like the error message could be improved to indicate a runtime failure.

The coalescing failure is the more pressing issue.

**Comment by leebenson** [comment]
Copying over from Slack -- the ordering of the expression seems to be a factor, too:

The Datadog syntax:

```
host:bar OR foo
```

Is roughly translated to:

```
(.host == "bar" || (match(.message, r'\bfoo\b') || (match(.custom.error.message, r'\bfoo\b') || (match(.custom.error.stack, r'\bfoo\b') || (match(.custom.title, r'\bfoo\b') || match(._default_, r'\bfoo\b')))))) ?? false
```

Which errors with:

```
unnecessary error coalescing operation
```

But flipping it around to be:

```
foo OR host:bar
```

Becomes:

```
((match(.message, r'\bfoo\b') || (match(.custom.error.message, r'\bfoo\b') || (match(.custom.error.stack, r'\bfoo\b') || (match(.custom.title, r'\bfoo\b') || match(._default_, r'\bfoo\b'))))) || .host == "bar") ?? false
```

Which succeeds.

A slightly terser example:

```
(.host == "this" || ((match(.custom.b, r'\btest.*\b') && .__datadog_tags.c == "that") && (.__datadog_tags.d == "the_other" && (.__datadog_tags.e >= 1 && .__datadog_tags.e <= 5)))) ?? false
```

Also throws:

```
unnecessary error coalescing operation
```

But removing one layer of parentheses around `match` succeeds:

```
(.host == "this" || (match(.custom.b, r'\btest.*\b') && .__datadog_tags.c == "that") && (.__datadog_tags.d == "the_other" && (.__datadog_tags.e >= 1 && .__datadog_tags.e <= 5))) ?? false
```

This is particularly brittle because expressions can be arbitrarily grouped in Datadog syntax, which we just wrap in a container -> group.

**Comment by JeanMertz** [comment]
> the ordering of the expression seems to be a factor, too

I haven't looked too deep into that example yet. But on first glance, this seems to make sense, given the issue I described above.

The OR operation considers the fallibility of the lhs expression, but _not_ the rhs expression, so swapping the expression will either expose, or hide the fallibility of that expression.
