### ISSUE TITLE
Support `logfmt` encoding on sinks

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8060]
A user requested support for the `logfmt` encoding on the `loki` sink.

A current workaround is to use `encode_logfmt` in VRL and then `encoding.codec = "text"` for sinks that support it.

We should pull out the encoding code from `encode_logfmt` to share it to ensure the implementation is the same.

**Comment by ktff** [comment]
#8983 extracted encoding code and enabled logfmt encoding for `loki` sink. The rest of the sinks for which logfmt can be enabled are:

- [ ] `aws_kinesis_firehose`
- [ ] `aws_kinesis_streams`
- [ ] `aws_s3`
- [ ] `aws_sqs`
- [ ] `azure_blob`
- [ ] `console`
- [ ] `http`
- [ ] `kafka`
- [ ] `nats`
- [ ] `papertrail`
- [ ] `pulsar`
- [ ] `redis`
- [ ] `splunk_hec`
- [ ] `aws_cloudwatch_logs`
- [ ] `file`
- [ ] `gcp_cloud_storage`
- [ ] `humio_logs`
- [ ] `humio_metrics`
- [ ] `socket`

Now the question is, does it make sense to support `logfmt` for all of them?

This ties to encoding `metric`. Currently while logs will have same output going through remap or through this, metrics won't. The issue is in that when we are transforming Metric into a vrl Value [the `MetricValue` part of Metric isn't transformed completely](https://github.com/timberio/vector/blob/97f8eb75b7475f66780da348ae894a079d9c60cc/lib/vector-core/src/event/metric.rs#L284-L300). So if someone tries to encode through remap it will have different result than if it would go through this encoding. Some solutions would be:
* Add missing transformation for metrics into vrl Value. 
* Modify encode logfmt process to match vrl transformation. This would be quite hacky.
* Enable `logfmt` encoding only for events. This would move the issue forward while metrics can be done later.

Implementing for logs now, while waiting for vrl to do the complete transformation seems like the best option to me.

cc. @JeanMertz

**Comment by jszwedko** [comment]
This is supported now via the [logfmt codec](https://github.com/vectordotdev/vector/blob/master/lib/codecs/src/encoding/format/logfmt.rs).
