### ISSUE TITLE
Add `is_json` VRL function

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8123]
Requested by user in discord: https://discord.com/channels/742820443487993987/746070591097798688/860600579721134121

We currently support this through something like:

```
_, err = parse_json(.message)
if err != nil {
  // is json
}
```

But I think this is likely to be fairly inefficient since it will still allocate and do the parsing. 

There is [an example](https://users.rust-lang.org/t/serde-json-checking-syntax-of-json-file/16265/4) of using `serde::de::IgnoredAny` to just check if the string is valid JSON:

```
    let _: serde::de::IgnoredAny = serde_json::from_str(&s).unwrap_or_else(|e| {
        eprintln!("Json: '{}'\nError: {}",s, e);
        ::std::process::exit(1);
    });
```

It seems to be more efficient based on the comments:

```
It saves a lot of time. Before it took 1.54 secs to parse an 100 MB file. Now it takes 0.44 secs to parse the same file.
```

**Comment by JeanMertz** [comment]
The only reservation I have is that currently all `is_<type>` functions are used to validate _value types_, whereas this would validate the _encoding type_.

Just riffing, maybe we want `is_encoding(.value, "json")`, which we can later expand to other types of encoding?

But, I also strongly feel that checking for JSON (and other encoding formats) is a common enough pattern in observability data that we'll likely want to make it as easy as possible, which `is_json` certainly does.

The more I think about this, the more I'm leaning towards `is_json`, so if anyone else has a better argument _not_ to do this, please speak up 😄

(another alternative, which would strike a balance between the two is `is_json_encoded`, it's a bit more annoying to type, but does better encapsulate its meaning, since it would check if the provided **string** type contains **json encoded** data)

**Comment by spencergilbert** [comment]
Ergonomics wise, I think that users generally would think of it as a "json value" so `is_json` sounds good to me
