### ISSUE TITLE
Ensure `datadog_metrics` sink handles all metrics types

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8493]
It has been reported that it does not handle histograms. We should address this and identify any other missing metrics support.

We should consider if we could be sending distributions directly to Datadog as well which could involve some refactoring of the internal metrics models.

**Comment by spencergilbert** [comment]
https://docs.datadoghq.com/metrics/types/?tab=count#metric-types

**Comment by spencergilbert** [comment]
It appears that we don't support `summary|aggregated_summary` in this sink

**Comment by chapmanc** [comment]
@spencergilbert Just checking in to see if this will be addressed soon? It's a big problem for us to not have summaries. We have verified that in `vector 0.19.0` the `datadog_metrics` sink is ignoring all `summaries`.

**Comment by jszwedko** [comment]
Closed by https://github.com/vectordotdev/vector/pull/9178

@chapmanc can you open a bug report if you aren't seeing the summaries reported? That work was completed for 0.18.0, we just forgot to close this issue. You can see how it is converted and published to Datadog here as sum/count/percentiles:

https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/encoder.rs#L468-L509

**Comment by tobz** [comment]
(Switching over to this issue because the other is specifically about histograms, which the `datadog_metrics` sink _does_ handle.)

@chapmanc So we dug into this a little more and although we haven't yet even tried to reproduce your issue, we're pretty sure this _is_ a legitimate bug.

Essentially, the way we normalize metrics internally does not have a meaningful way to handle normalizing an aggregated summary as a whole.  This essentially causes us to not emit them in certain cases i.e. when a sink like `datadog_metrics` wants incremental metrics only, whereas aggregated summaries are only ever absolute, and so on.

We've opened #12126 to track this specific deficiency, which you can follow to track our progress on fixing it. It's not a terribly complicated issue, so it may be something we can fix by the next release, or as part of a point release for 0.21.
