### ISSUE TITLE
`datadog_metrics` sink does not send histograms to Datadog

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vector#8626]
We've observed that histograms sent from the `datadog_metrics` sink do not end up correctly in Datadog.

This is related to:

* https://github.com/timberio/vector/issues/8493
* https://github.com/timberio/vector/issues/7283

But as a first step I think we could just fix the existing implementation. If we find we cannot do this and should instead prioritize switching to sketches as mentioned in #7283 we can close this.

**Comment by jszwedko** [comment]
Similar to https://github.com/vectordotdev/vector/issues/8493#issuecomment-1091971106 this was implemented in https://github.com/vectordotdev/vector/pull/9178 which was released as 0.18.0. Histograms are converted to Datadog's native sketch format here: https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/normalizer.rs#L22-L29

If you are still seeing issues though, a bug report is welcome 🙂

**Comment by chapmanc** [comment]
@jszwedko I will open a bug but in the same list I am not seeing the `AggregatedSummary` type in [that list ](https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/normalizer.rs#L18-L34)

Summary type: https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/event/metric.rs#L210-L219

**Comment by tobz** [comment]
> @jszwedko I will open a bug, but in the same list you linked I am not seeing the `AggregatedSummary` type in [that list ](https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/normalizer.rs#L18-L34i)
> 
> Summary type: https://github.com/vectordotdev/vector/blob/master/lib/vector-core/src/event/metric.rs#L210-L219

The catch-all match arm on [normalizer.rs:34](https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/normalizer.rs#L18-L34) handles it, because we just treat it incrementally. Over in [encoder.rs:468-509](https://github.com/vectordotdev/vector/blob/82ea429a7fe42ce48c5d52dffb2801507c6ca81b/src/sinks/datadog/metrics/encoder.rs#L468-L509) is where we actually handle generating series metrics specifically for aggregated summaries, which is that we emit their count, sum, and a gauge for each quantile.

**Comment by chapmanc** [comment]
Thanks, will continue debugging and see if I missed anything before opening a bug. Your help is really appreciated 😄
