### ISSUE TITLE
`KeyPartitioner` should emit `Arc<str>` instead of `String`

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#9130]
For any code using `Batcher`, a `Partitioner` implementation must be used that generates a partition key for a given event.  That partition key will always be cloned when an item is inserted into a batch, due to needing the key both for finding/creating the internal batch as well as inserting a timeout for the batch.

In the case of `KeyPartitioner`, we're emitting a `String` partition key, which has the potential to be very long: some Vector users will end up with partition keys that are over 128 bytes long.  Cloning this is still "cheap", but we could make it even cheaper by wrapping the resulting `String` into an `Arc<str>`.

**Comment by jszwedko** [comment]
Closing since our performance improvements are typically driven by performance analysis and this issue would be unlikely to be picked up without that motivation. I brought up the idea internally of just leaving a code comment for this sort of thing for us to find if we do go to optimize a particular area.
