### ISSUE TITLE
Add an option to the Prometheus sinks to only export metrics that have recently changed

### ISSUE THREAD

**Issue by StephenWakely** [vectordotdev/vector#9135]
From a conversation on [Discord](https://discord.com/channels/742820443487993987/746070591097798688/887265555533410334).

A user is collecting a ton of metrics which adds up to 100MB+ each time. It would be very useful if the sink could only export metrics that have recently changed which should significantly reduce the amount of data sent each time.

**Comment by jszwedko** [comment]
🤔 I believe the expectation of prometheus endpoints is that they always export the full set of metrics so I'm not sure we'd want to do this. I did discover that Prometheus has a protobuf format too though (https://github.com/Showmax/prometheus-docs/blob/master/content/docs/instrumenting/exposition_formats.md) which could help slim down the payloads.

**Comment by ocrlgv** [comment]
Full set of metrics but should be valid. Even prometheus will scrape a metrics and if not seen again will mark as stale, then after 5min (that I've seen) it removes it. So if prometheus even removes it. test it by sending a custom single metric to prometheus, graph it in Grafana and you will see it plots the same value for 5min before it disappears.

A percentage of the metrics being scraped are hosts that have spun up, pushed metrics to vector and eventually shut down. Those hosts now forever lives on the export unless vector is restarted.
I don't see the need to have such entries forever on the /metrics end.

The end goal for me is to have push to aws prometheus, so this is an interim issue since I can't send directly to AWS prometheus yet,

**Comment by jszwedko** [comment]
Gotcha, thanks for the context @ocrlgv . I propose we close this and prioritize #6204 . Would that work for you? I think the normal expectation for Prometheus scrape endpoints is that they expose all metrics.

**Comment by ocrlgv** [comment]
yeah, sounds good. #6204 is the main reason why I had to use this method.

**Comment by jszwedko** [comment]
Thanks @ocrlgv !
