### ISSUE TITLE
Send metrics data to Prometheus through Kafka

### ISSUE THREAD

**Issue by manuvnair** [vectordotdev/vector#9186]
We would like to use “host_metrics” source to generate metrices then transform to “metrics_to_log” before sinking (with json ecoded) to a Kafka topic. Then while consuming from Kakfa, transform using “json_parser” and then perform “log_to_metric” transformation before sinking to Prometheus. However the log_to_metric transformation is not working as expected. 

Can we have a feature to sink metrics data to Kafka and then consumed for Prometheus.
Vector>Kafka>Vector>Prometheus

**Comment by jszwedko** [comment]
Hi @manuvnair !

We are working to support this use-case as part of https://github.com/vectordotdev/vector/issues/8494 which'll allow just sending metrics through Kafka and having Vector correctly serialize and deserialize them. There is a hacky workaround which involves using `metric_to_log` to convert to a log event, as you have, and then a `lua` transform to convert back into a metric: https://github.com/vectordotdev/vector/discussions/7689#discussioncomment-885366

I'll close this since this work is represented by https://github.com/vectordotdev/vector/issues/8494 but feel free to leave any additional thoughts or questions.

**Comment by tobz** [comment]
This work is now represented by #9930. We plan on exploring a way to simply expose the ability to decode/encode native Vector events. Instead of accepting a particular shape of data from an arbitrary source/sink, the native Vector event representation would be used instead. This is both simpler to implement and would result in higher performance, because ultimately, all data flowing into Vector is converted to our native internal representation.

**Comment by awangc** [comment]
@tobz with #9930 closed, does vector now support the question originally posted? That is, does vector now support

vector -> kafka -> vector -> Prometheus 

via logs_to_metrics in the last hop?

**Comment by tobz** [comment]
Well, you could always do the aforementioned topology if you were sending logs through up until the very last Vector that ultimately did the Prometheus part.

Whil I'm not sure if the Kafka sink/source can use the native codecs yet, what they would/I'll allow you to do is handle things as metrics in the very first Vector part of that topology, so `logs_to_metrics` in the _first_ hop, if they were initially coming in as logs.

**Comment by spencergilbert** [comment]
As of `0.23` (expected release Monday) we should have complete codec support for sinks and sources to support that 👍
