### ISSUE TITLE
See if we can change `Value::Object` from `BTreeMap<String, Value` to `BTreeMap<Cow<'static, str>, Value>`.

### ISSUE THREAD

**Issue by spencergilbert** [vectordotdev/vector#9287]
Random note: I think we should add a tracking issue to see if we can change `Value::Object` from `BTreeMap<String, Value` to `BTreeMap<Cow<'static, str>, Value>`.

That is, we have more and more places where we add static strings to a map, but then allocate them on the heap because of the current signature of the map.

_Originally posted by @JeanMertz in https://github.com/vectordotdev/vector/pull/9269#discussion_r712712222_

**Comment by jszwedko** [comment]
Closing since our performance improvements are typically driven by performance analysis and this issue would be unlikely to be picked up without that motivation. I brought up the idea internally of just leaving a code comment for this sort of thing for us to find if we do go to optimize a particular area.
