### ISSUE TITLE
chore(architecture): optimize `EncodingConfiguration::apply_only_fields`

### ISSUE THREAD

**Issue by tobz** [vectordotdev/vector#9472]
Looking at https://github.com/vectordotdev/vector/blob/master/src/sinks/util/encoding/mod.rs#L71-L74, it should be possible to write an iterator combinator that allows two iterators to be directly checked in a `starts_with` fashion.  This would let us avoid having to allocate when collecting the path components for `field`.

Probably a very small optimization, but we can essentially get it for free, so why not?

**Comment by jszwedko** [comment]
cc/ @pablosichert could be something to keep an eye out for when you start in on the encoding work.

**Comment by jszwedko** [comment]
Closing since our performance improvements are typically driven by performance analysis and this issue would be unlikely to be picked up without that motivation. I brought up the idea internally of just leaving a code comment for this sort of thing for us to find if we do go to optimize a particular area.
