### ISSUE TITLE
Allow to encode/decode network traffic between vector client and server with zstd/snappy/brotli 

### ISSUE THREAD

**Issue by SCREEN88** [vectordotdev/vector#9558]
### Current Vector Version

```
0.17.0
```
### Use-cases
Currently, we are sending traffic from several dozen clients to a single vector server, at the moment we are approaching 3 Gbps on the input. It would be great if we could start compressing outgoing traffic on the client and automatically decompress it on the server to reduce the load on the network.

### Attempted Solutions
No solution

### Proposal
Add options for client to encode traffic with desired codec. Auto decode traffic on server.

**Comment by tobz** [comment]
For anyone looking to contribute:

Since we're using `tonic` now for the v2 of the `vector` source and sink, this could potentially be as simple as configuring the server/client objects to support compression: [client::Grpc::send_gzip](https://docs.rs/tonic/0.6.1/tonic/client/struct.Grpc.html#method.send_gzip) and [server::Grpc::accept_gzip](https://docs.rs/tonic/0.6.1/tonic/server/struct.Grpc.html#method.accept_gzip).
