### ISSUE TITLE
Clarify `BytesReceived` event and correct behavior of sources

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vector#9855]
Pursuant to https://github.com/vectordotdev/vector/pull/9637#issuecomment-948946241 the component spec needs to be amended to indicate the `BytesReceived` event should only report valid filtered data, and all sources need to be audited to ensure this behavior.

Two questions remain:
1. Do we want a separate event and metric for the raw bytes received?
2. Do we want to distinguish between bytes filtered because of invalid data and bytes filtered due to configuration parameters?

cc @binarylogic @jszwedko

**Comment by jszwedko** [comment]
Thanks for opening this @bruceg !

My thoughts are that we start with just instrumenting the bytes successfully received (that is: not filtered or dropped because they are invalid) as `component_bytes_receieved_total`.

We can then follow up later date with a metric for bytes dropped because they were filtered or invalid. I think this is not as pressing.
