### ISSUE TITLE
Soak 'comparison' SHA is not accurate

### ISSUE THREAD

**Issue by blt** [vectordotdev/vector#9940]
Consider [this comment](https://github.com/vectordotdev/vector/pull/9936#issuecomment-962223478). The two commits listed are https://github.com/vectordotdev/vector/commit/1333fa30e5b2d26db41a99bd5ec2331de9756b67 and https://github.com/vectordotdev/vector/commit/83cfaf897162caa75e7067bdfab58e4aa121dfc2. The later, the comparison SHA, does not exist. Not only does it not exist it doesn't exist _in the PR_. This is peculiar as we use `github.sha` for the comparison SHA. 

What we want is the last user visible SHA to be used as the comparison in soaking, else the user can't actually compare anything.

**Comment by blt** [comment]
@jszwedko @tobz you both know Github Actions pretty well. Don't suppose you have any notions here?

**Comment by blt** [comment]
Ah, meant to CC @spencergilbert as well.

**Comment by jszwedko** [comment]
@blt Ah, I think this is because Github Actions merges in master on PR builds. Very confusingly `github.sha` is documented as:

> The commit SHA that triggered the workflow run.

But really I believe it will be the merge commit SHA. Same goes for `$GITHUB_SHA`. See https://github.community/t/github-sha-isnt-the-value-expected/17903

I think, instead, you can use `github.event.pull_request.head.sha`. This is only set for PRs, which is fine for soaks as they are, but is something we'd need to make sure to update if we ever start running the soak tests on pushes to `master`.

**Comment by blt** [comment]
Re-assigning to @jszwedko as he's very kindly accepted taking this on.
