### ISSUE TITLE
Remove the `pipelines` namespace in the `pipelines` transform

### ISSUE THREAD

**Issue by binarylogic** [vectordotdev/vector#9993]
In the [original examples for the `pipelines` configuration](https://github.com/vectordotdev/pipelines_config_example/pull/2), we [purposefully omitted the additional namespace](https://github.com/vectordotdev/pipelines_config_example/pull/3/files#diff-6767eb992e99aeca4f2170ef90d5d241c03fde6e5f3cea1c9b874cc65c7fd22bR20) for defining pipelines to keep things simple. For example:

```
[[transforms.processing.logs.pipelines.envoy.transforms]]
```

Should be:

```
[[transforms.processing.logs.envoy.transforms]]
```

This was intentional. This keeps the definitions of pipelines simpler, especially when users take advantage using the new implicit file-based namespace for defining pipelines (one file per pipeline). And I realize this poses a namespace clash with other pipeline options, like `order`, butI think it's worth it. We're trading the UX (which is most important) to solve an extreme edge case, which does not make sense.

Specifically I want to:

- [ ] Remove the `pipelines` namespace so that defining a pipeline follows this template `transforms.<transform-id>.logs.<pipeline-id>`
- [ ] Reserve the `order` option and error if a `pipeline` using the `order` id.

**Comment by jdrouet** [comment]
What worries me the most is that people seem to have issues understanding what is the `pipelines` transform.
In Vectors configuration, we usually have the type of the object followed by its name (`sources.foo`, `transforms.bar`, ...) so to me it was making it more explicit, easier to understand, to also prefix the pipeline name by its type, so that when users see `transforms.foo.logs.pipelines.bar`, they understand that they are defining the pipeline bar.
And as you said, this also avoid any conflict with the `logs|metrics|traces` section's options (we should find a name for this). If we want to add some more options later, we are kind of blocking it and we might run into other issues later. 🤔

**Comment by binarylogic** [comment]
Yeah, those are good points. I'm curious what @jszwedko thinks?

**Comment by jszwedko** [comment]
👍 I'm inclined to leave `pipelines` in for now to avoid issues with name collisions.
